---
# .swiftlint.yml (proposed next pass)
included:
  - Sources
  - Tests

disabled_rules:
  - inclusive_language

opt_in_rules:
  - empty_count
  - explicit_init
  - first_where
  - operator_usage_whitespace
  - duplicate_imports
  - trailing_newline
  - trailing_comma
  - statement_position
  - comma
  - unused_import
  - redundant_optional_initialization
  - redundant_type_annotation
  - explicit_self
  - explicit_acl
  - let_var_whitespace
  - todo
  - discouraged_optional_collection
  - attributes
  - modifier_order

explicit_acl:
  excluded:
    - Tests/**


identifier_name:
  min_length: 2
  allowed_symbols: ["_"]
  excluded: ["id", "x", "y", "i", "j", "k", "db", "IO"]

line_length:
  warning: 120
  error: 140
  ignores_comments: true
  ignores_function_declarations: true
  ignores_urls: true

trailing_whitespace:
  ignores_empty_lines: true

file_length:
  warning: 500
  error: 1200

type_body_length:
  warning: 300
  error: 600

function_body_length:
  warning: 80
  error: 160

cyclomatic_complexity:
  ignores_case_statements: true
  warning: 12
  error: 20

nesting:
  type_level:
    warning: 2
    error: 3
  statement_level:
    warning: 5
    error: 7

force_cast: error
force_try: error

reporter: "github-actions-logging"