// swift-tools-version: 6.0
//
//  Package.swift
//  VoiceKit
//
//  Generated by GPT-5 (OpenAI) — collaborator: rdoggett
//  date: 09-13-2025
//

import PackageDescription

let package = Package(
    name: "VoiceKit",
    defaultLocalization: "en",
    platforms: [
        .iOS("17.0"),
        .macOS("14.0")
    ],
    products: [
        .library(name: "VoiceKitCore", targets: ["VoiceKitCore"]),
        .library(name: "VoiceKitUI", targets: ["VoiceKitUI"])
    ],
    dependencies: [
    ],
    targets: [
        .target(
            name: "VoiceKitCore",
            path: "Sources/VoiceKitCore"
        ),
        .target(
            name: "VoiceKitUI",
            dependencies: ["VoiceKitCore"],
            path: "Sources/VoiceKitUI"
        ),
        .testTarget(
            name: "VoiceKitCoreTests",
            dependencies: ["VoiceKitCore"],
            path: "Tests/VoiceKitCoreTests"
        ),
        .testTarget(
            name: "VoiceKitUITests",
            dependencies: ["VoiceKitCore", "VoiceKitUI"],
            path: "Tests/VoiceKitUITests"
        )
    ],
    swiftLanguageModes: [
        .v6
    ]
)
