// swift-tools-version: 6.0
//
//  Package.swift
//  VoiceKit
//
//  Generated by GPT-5 (OpenAI) — collaborator: rdoggett
//  date: 09-11-2025
//

import PackageDescription

let package = Package(
    name: "VoiceKit",
    defaultLocalization: "en",
    platforms: [
        .iOS("17.0"),
        .macOS("14.0")
    ],
    products: [
        // Non-UI core: protocols, RealVoiceIO, ScriptedVoiceIO, RecognitionContext, TTS models, NameResolver, NameMatch, actors.
        .library(name: "VoiceKitCore", targets: ["VoiceKitCore"]),
        // Optional UI: VoicePicker and profiles store (depends on Core).
        .library(name: "VoiceKitUI", targets: ["VoiceKitUI"])
    ],
    dependencies: [
        // No external dependencies for v0
    ],
    targets: [
        .target(
            name: "VoiceKitCore",
            path: "Sources/VoiceKitCore"
            // Swift 6 language mode is set at the package level below.
            // If you had per-target settings like experimental flags, you could add swiftSettings here.
        ),
        .target(
            name: "VoiceKitUI",
            dependencies: ["VoiceKitCore"],
            path: "Sources/VoiceKitUI"
        ),
        .testTarget(
            name: "VoiceKitCoreTests",
            dependencies: ["VoiceKitCore"],
            path: "Tests/VoiceKitCoreTests"
        )
    ],
    // SwiftPM 6: use swiftLanguageModes (replaces swiftLanguageVersions)
    swiftLanguageModes: [
        .v6
    ]
)
