// swift-tools-version: 6.0
//
//  Package.swift
//  VoiceKit
//
//  Generated by GPT-5 (OpenAI) — collaborator: rdoggett
//  date: 09-13-2025
//

import PackageDescription

let package = Package(
    name: "VoiceKit",
    defaultLocalization: "en",
    platforms: [
        .iOS("17.0"),
        .macOS("14.0")
    ],
    products: [
        .library(name: "VoiceKit", targets: ["VoiceKit"]),
        .library(name: "VoiceKitUI", targets: ["VoiceKitUI"])
    ],
    dependencies: [
    ],
    targets: [
        .target(name: "TestSupport", path: "Sources/TestSupport"),
        .target(
            name: "VoiceKit",
            path: "Sources/VoiceKit"
        ),
        .target(
            name: "VoiceKitUI",
            dependencies: ["VoiceKit"],
            path: "Sources/VoiceKitUI"
        ),
        .testTarget(
            name: "VoiceKitTests",
            dependencies: ["VoiceKit", "TestSupport"],
            path: "Tests/VoiceKitTests"
        ),
        .testTarget(
            name: "VoiceKitUITests",
            dependencies: ["VoiceKitUI", "VoiceKit", "TestSupport"],
            path: "Tests/VoiceKitUITests"
        ),
    ],
    swiftLanguageModes: [
        .v6
    ]
)
