//
//  ChorusLabTargetTimeRow.swift
//  VoiceKitUI
//
//  Target-time control row used in Chorus Lab. Shows the target duration (s),
//  a stepper to adjust it, and the last measured actual duration.
//  Generated by GPT-5 (OpenAI) — collaborator: rdoggett
//  date: 10-31-2025
//

import SwiftUI

@MainActor
public struct ChorusLabTargetTimeRow: View {
    @Binding var targetSeconds: Double
    var isPlaying: Bool
    var lastChorusSeconds: Double?

    // Inject small layout/tuning knobs so this view has no dependency on ChorusLabView.Metrics.
    var targetRange: ClosedRange<Double>
    var targetStep: Double
    var actualMinWidth: CGFloat

    public var body: some View {
        HStack(spacing: 8) {
            Text("Target Time")
                .font(.footnote)
                .lineLimit(1)
                .layoutPriority(1)
            Text(targetSeconds.asSeconds())
                .monospacedDigit()
                .foregroundStyle(.secondary)
            Stepper(value: $targetSeconds, in: targetRange, step: targetStep) {
                EmptyView()
            }
            .labelsHidden()
            .controlSize(.mini)
            .accessibilityLabel("Target time")
            .accessibilityHint("Adjust the target duration in seconds")

            Spacer()
            HStack(spacing: 6) {
                if isPlaying {
                    ProgressView().controlSize(.mini)
                }
                Text(lastChorusSeconds.map { $0.asSeconds() } ?? "—s")
                    .monospacedDigit()
                    .foregroundStyle(.secondary)
                    .lineLimit(1)
            }
            .frame(minWidth: actualMinWidth, alignment: .trailing)
            .accessibilityLabel("Actual time")
            .accessibilityValue(lastChorusSeconds.map { $0.asSeconds() } ?? "Not available")
        }
        .padding(.horizontal)
        .padding(.bottom, 4) // matches Metrics.Padding.headerV
    }
}

#if DEBUG
@MainActor
internal struct ChorusLabTargetTimeRow_Previews: PreviewProvider {
    private struct PreviewWrapper: View {
        @State var targetSeconds: Double = 2.50
        @State var isPlaying: Bool = false
        @State var lastChorusSeconds: Double? = 2.47
        var body: some View {
            VStack(spacing: 8) {
                ChorusLabTargetTimeRow(
                    targetSeconds: $targetSeconds,
                    isPlaying: isPlaying,
                    lastChorusSeconds: lastChorusSeconds,
                    targetRange: 0.5...10.0,
                    targetStep: 0.05,
                    actualMinWidth: 56
                )
                .padding(.horizontal)
                .padding(.vertical, 8)
            }
        }
    }

    internal static var previews: some View {
        PreviewWrapper()
            .previewDisplayName("ChorusLabTargetTimeRow · iPhone SE (3rd gen)")
            .previewDevice("iPhone SE (3rd generation)")
    }
}
#endif
