//
//  ChorusLabGlobalAdjustmentsView.swift
//  VoiceKit
//
//  Global tuning sliders for Chorus Lab (speed × and pitch offset).
//  Generated by GPT-5 (OpenAI) — collaborator: rdoggett
//  date: 10-31-2025
//

import SwiftUI

@MainActor
public struct ChorusLabGlobalAdjustmentsView: View {
    @Binding var rateScale: Double
    @Binding var pitchOffset: Double
    var speedRange: ClosedRange<Double>
    var pitchOffsetRange: ClosedRange<Double>
    var sliderStep: Double
    var onChange: () -> Void

    // Public memberwise initializer; declaring this in-struct suppresses the synthesized init
    // and avoids redeclaration/ambiguity with a same-signature extension initializer.
    public init(rateScale: Binding<Double>,
                pitchOffset: Binding<Double>,
                speedRange: ClosedRange<Double>,
                pitchOffsetRange: ClosedRange<Double>,
                sliderStep: Double,
                onChange: @escaping () -> Void) {
        self._rateScale = rateScale
        self._pitchOffset = pitchOffset

        self.speedRange = speedRange
        self.pitchOffsetRange = pitchOffsetRange

        self.sliderStep = sliderStep
        self.onChange = onChange
    }

    public var body: some View {
        VStack(spacing: 8) {
            TunerSliderRow(
                title: "Speed",
                systemImage: "speedometer",
                value: $rateScale,
                range: speedRange,
                step: sliderStep,
                formatted: { value in value.asMultiplier() }
            )
            .onChange(of: rateScale) { _, _ in onChange() }

            TunerSliderRow(
                title: "Pitch",
                systemImage: "waveform.path.ecg",
                value: $pitchOffset,
                range: pitchOffsetRange,
                step: sliderStep,
                formatted: { off in (1.0 + off).formatted() }
            )
            .onChange(of: pitchOffset) { _, _ in onChange() }
        }
    }
}

#if DEBUG
@MainActor
internal struct ChorusLabGlobalAdjustmentsView_Previews: PreviewProvider {
    private struct PreviewWrapper: View {
        @State var rateScale: Double = 1.00
        @State var pitchOffset: Double = 0.00
        var body: some View {
            VStack(spacing: 10) {
                ChorusLabGlobalAdjustmentsView(
                    rateScale: $rateScale,
                    pitchOffset: $pitchOffset,
                    speedRange: 0.5...1.5,
                    pitchOffsetRange: -0.5...0.5,
                    sliderStep: 0.01,
                    onChange: {}
                )
                .padding(.horizontal)
                .padding(.vertical, 8)
            }
        }
    }

    internal static var previews: some View {
        PreviewWrapper()
            .previewDisplayName("ChorusLabGlobalAdjustmentsView · iPhone SE (3rd gen)")
            .environment(\.locale, .init(identifier: "en_US"))
            .previewDevice("iPhone SE (3rd generation)")
    }
}
#endif
