//
//  RealVoiceIO+TTSConformance.swift
//  VoiceKit
//
//  Declares AVSpeechSynthesizerDelegate conformance in a plain (nonisolated) extension.
//  Implementations live in RealVoiceIO+TTSImpl.swift and marshal to @MainActor.
//
//  Generated by GPT-5 (OpenAI) - collaborator: rdoggett
//  date: 09-18-2025
//

import Foundation
@preconcurrency import AVFoundation

extension RealVoiceIO: AVSpeechSynthesizerDelegate {}
