//
//  RealVoiceIO+Trimming.swift
//  VoiceKit
//
//  Generated by GPT-5 (OpenAI)
//  collaborator: rdoggett
//  date: 09-15-2025
//

import Foundation
@preconcurrency import AVFoundation
import Accelerate

@MainActor
extension RealVoiceIO {

    internal func trimAudioSmart(inputURL: URL,
                                 sttStart: Double?,
                                 sttEnd: Double?,
                                 prePad: Double,
                                 postPad: Double) -> URL? {
        do {
            let inFile = try AVAudioFile(forReading: inputURL)
            let sampleRate = inFile.fileFormat.sampleRate
            let totalFrames = inFile.length
            let duration = Double(totalFrames) / sampleRate

            var bounds = computeTrimBounds(sttStart: sttStart,
                                          sttEnd: sttEnd,
                                          duration: duration,
                                          inFile: inFile,
                                          totalFrames: totalFrames)
            bounds.start = max(0, bounds.start - prePad)
            bounds.end = min(duration, bounds.end + postPad)
            log(.info, "trimAudioSmart finalWindow start=\(bounds.start) end=\(bounds.end) duration=\(duration)")

            guard bounds.end > bounds.start else { return inputURL }

            let outURL = inputURL.deletingPathExtension().appendingPathExtension("trim.caf")
            try writeAudioTrimmed(from: inFile,
                                 to: outURL,
                                 startTime: bounds.start,
                                 endTime: bounds.end,
                                 sampleRate: sampleRate)
            return outURL
        } catch {
            return inputURL
        }
    }

    private func computeTrimBounds(sttStart: Double?,
                                   sttEnd: Double?,
                                   duration: Double,
                                   inFile: AVAudioFile,
                                   totalFrames: AVAudioFramePosition) -> (start: Double, end: Double) {
        var fallback = (sttStart == nil || sttEnd == nil || sttEnd! <= sttStart!)
        var start = sttStart ?? 0
        var end = sttEnd ?? duration

        if !fallback, let startTime = sttStart, let endTime = sttEnd {
            let span = max(0, endTime - startTime)
            let nonSpeech = max(0, duration - span)
            if nonSpeech > max(2.0, span * 0.5) {
                fallback = true
            }
        }

        let debugMessage = """
            trimAudioSmart sttStart=\(sttStart ?? -1) \
            sttEnd=\(sttEnd ?? -1) \
            rawDuration=\(String(format: "%.3f", duration))
            """
        log(.info, debugMessage)

        if fallback {
            if let bounds = energyTrimBounds(inFile: inFile,
                                            sampleRate: inFile.fileFormat.sampleRate,
                                            totalFrames: totalFrames,
                                            thresholdDB: -35,
                                            chunk: 8192) {
                start = bounds.start
                end = max(bounds.end, bounds.start + 0.1)
                log(.info, "trimAudioSmart energyBounds start=\(bounds.start) end=\(bounds.end)")
            } else {
                start = 0
                end = duration
            }
        }
        return (start, end)
    }

    private func writeAudioTrimmed(from inFile: AVAudioFile,
                                   to outURL: URL,
                                   startTime: Double,
                                   endTime: Double,
                                   sampleRate: Double) throws {
        let sampleRate = inFile.fileFormat.sampleRate
        let startFrame = AVAudioFramePosition(startTime * sampleRate)
        let endFrame = AVAudioFramePosition(endTime * sampleRate)

        let outFile = try AVAudioFile(forWriting: outURL, settings: inFile.fileFormat.settings)

        inFile.framePosition = startFrame
        let chunkSize: AVAudioFrameCount = 8192
        while inFile.framePosition < endFrame {
            let remaining = AVAudioFrameCount(endFrame - inFile.framePosition)
            let frames = min(chunkSize, remaining)
            let format = inFile.processingFormat
            guard let buffer = AVAudioPCMBuffer(pcmFormat: format, frameCapacity: frames) else {
                break
            }
            try inFile.read(into: buffer, frameCount: frames)
            if buffer.frameLength == 0 { break }
            buffer.frameLength = frames
            try outFile.write(from: buffer)
        }
    }

    // Extracted energy-based trim bounds to reduce cyclomatic complexity of trimAudioSmart.
    // Scans the file in chunks and returns the first non-silent timestamp and last non-silent timestamp.
    private func energyTrimBounds(inFile: AVAudioFile,
                                  sampleRate: Double,
                                  totalFrames: AVAudioFramePosition,
                                  thresholdDB: Float,
                                  chunk: AVAudioFrameCount) -> (start: Double, end: Double)? {
        let targetFormat = inFile.processingFormat
        inFile.framePosition = 0

        // First pass: collect (timestamp, dB) samples across the file.
        struct Sample { let ts: Double; let db: Float }
        var samples: [Sample] = []
        samples.reserveCapacity(Int(totalFrames / AVAudioFramePosition(chunk)) + 1)

        while inFile.framePosition < totalFrames {
            let remaining = AVAudioFrameCount(totalFrames - inFile.framePosition)
            let frames = min(chunk, remaining)
            guard let buf = AVAudioPCMBuffer(pcmFormat: targetFormat, frameCapacity: frames) else { break }
            do {
                try inFile.read(into: buf, frameCount: frames)
            } catch {
                break
            }
            if buf.frameLength == 0 { break }
            let ts = Double(inFile.framePosition - Int64(frames)) / sampleRate

            if let ch = buf.floatChannelData?.pointee {
                var ms: Float = 0
                vDSP_measqv(ch, 1, &ms, vDSP_Length(buf.frameLength))
                let db: Float = ms <= 0 ? -160 : 10 * log10f(ms)
                samples.append(Sample(ts: ts, db: db))
            }
        }

        guard !samples.isEmpty else { return nil }

        // Derive a dynamic threshold: 10 dB above the quietest chunk,
        // but never lower than the explicit thresholdDB.
        let minDb = samples.map(\.db).min() ?? -160
        let dynamicThreshold = max(thresholdDB, minDb + 10)

        var foundStart: Double?
        var lastNonSilent: Double = 0

        for sample in samples where sample.db > dynamicThreshold {
            if foundStart == nil {
                foundStart = sample.ts
            }
            // Use chunk end as last-non-silent for this sample
            lastNonSilent = sample.ts + Double(chunk) / sampleRate
        }

        if let fs = foundStart {
            return (fs, lastNonSilent)
        } else {
            return nil
        }
    }
}
