//
//  RealVoiceIO.swift
//  VoiceKit
//
//  Main VoiceIO implementation with TTS and live STT.
//  - In CI/headless (IsCI.running): listen() uses a deterministic stub path.
//  - In apps on device/simulator: listen() uses the live AVAudioEngine + SFSpeechRecognizer pipeline.
//
//  Generated by GPT-5 (OpenAI) - collaborator: rdoggett
//  date: 09-18-2025
//

import Foundation
@preconcurrency import AVFoundation
import CoreGraphics
@preconcurrency import Speech
import Observation

@Observable
@MainActor
public final class RealVoiceIO: NSObject, TTSConfigurable, VoiceIO, TempoMeasurable {

    // MARK: - Observable state (VoiceIO protocol conformance)
    public var isSpeaking: Bool = false
    public var isListening: Bool = false
    public var transcript: String = ""
    public var audioLevel: CGFloat = 0
    public var pulse: CGFloat = 0
    public var statusMessage: String?

    // MARK: - Debug logging (opt-in)
    public enum LogLevel: Sendable {
        case info, warn, error
    }
    /// Optional logger. Set from the app to trace VoiceKit events.
    /// Example:
    ///   io.logger = { level, msg in print("[VoiceKit][\(level)] \(msg)") }
    @ObservationIgnored public var logger: ((LogLevel, String) -> Void)?

    @inline(__always)
    internal func log(_ level: LogLevel = .info, _ message: @autoclosure () -> String) {
        logger?(level, message())
    }

    // MARK: - Public config
    @ObservationIgnored public private(set) var config: VoiceIOConfig

    // MARK: - TTS state
    @ObservationIgnored internal var profilesByID: [String: TTSVoiceProfile] = [:]
    @ObservationIgnored internal var defaultProfile: TTSVoiceProfile?
    @ObservationIgnored internal var tuning: Tuning = .init()

    // AVSpeechSynthesizer is @ObservationIgnored: it must not enter the observation
    // registrar's withMutation path. AVFoundation's internal dispatch already conflicts
    // with Swift's cooperative thread pool (see DispatchQueue.main.async workaround in
    // RealVoiceIO+TTSImpl.swift); adding registrar overhead amplifies the problem.
    @ObservationIgnored internal var synthesizer: AVSpeechSynthesizer?

    // Continuation dictionaries are mutated at high frequency during speech synthesis;
    // keeping them out of the registrar avoids spurious SwiftUI invalidation and
    // reduces overhead on the critical TTS path.
    @ObservationIgnored internal var speakContinuations: [ObjectIdentifier: CheckedContinuation<Void, Never>] = [:]

    // Per-utterance timing (for duration measurement/calibration)
    @ObservationIgnored internal var ttsStartTimes: [ObjectIdentifier: TimeInterval] = [:]
    @ObservationIgnored internal var measureContinuations: [ObjectIdentifier: CheckedContinuation<TimeInterval, Never>] = [:]

    // Pulse animation phase accumulator (feeds into `pulse` via sine wave).
    // Ignored: intermediate accumulator; only `pulse` (the derived value) is observed.
    @ObservationIgnored internal var ttsPhase: CGFloat = 0

    // MARK: - Environment helpers

    /// Treat the iOS simulator like CI for live STT:
    /// many simulator/runtime combinations do not reliably support
    /// SFSpeechRecognizer + AVAudioEngine, and repeatedly fail with
    /// kAFAssistantErrorDomain recording errors. On real devices we
    /// still use the full live STT pipeline.
    internal static var isSimulator: Bool {
        #if targetEnvironment(simulator)
        return true
        #else
        return false
        #endif
    }

    // MARK: - Test/STT shim state

    // Recognition context captured for listen shim + live STT.
    // Internal so STT extension can read it.
    @ObservationIgnored internal var recognitionContext: RecognitionContext = .init()

    // MARK: - STT live state

    @ObservationIgnored internal var speechRecognizer: SFSpeechRecognizer? = SFSpeechRecognizer(locale: .autoupdatingCurrent)
    @ObservationIgnored internal var audioEngine: AVAudioEngine?
    @ObservationIgnored internal var recognitionRequest: SFSpeechAudioBufferRecognitionRequest?
    @ObservationIgnored internal var recognitionTask: SFSpeechRecognitionTask?

    @ObservationIgnored internal var hasFinishedRecognition = false
    @ObservationIgnored internal var firstSpeechStart: Double?
    @ObservationIgnored internal var lastSpeechEnd: Double?

    @ObservationIgnored internal var listenOverallTask: Task<Void, Never>?
    @ObservationIgnored internal var listenInactivityTask: Task<Void, Never>?

    // Tracks recent speech activity based on input energy.
    @ObservationIgnored internal let sttActivityTracker = STTActivityTracker()

    // Per-listen recording state for live STT
    @ObservationIgnored internal var rawRecordingURL: URL?
    @ObservationIgnored internal var currentListenShouldRecord = false

    // Continuation for the current live listen (non-CI path)
    @ObservationIgnored internal var listenCont: CheckedContinuation<VoiceResult, Error>?

    // MARK: - Boosted clip playback state

    /// Pending continuations waiting for clip completion.
    @ObservationIgnored internal var clipWaitersState: [CheckedContinuation<Void, Error>] = []

    /// AVAudioPlayer for short-clip (boosted) playback.
    @ObservationIgnored internal var avClipPlayerState: AVAudioPlayer?

    /// AVAudioPlayerNode (retained for test compatibility; not actively used).
    @ObservationIgnored internal var clipPlayerNodeState: AVAudioPlayerNode?

    /// Flag tracking whether this clip session has completed.
    @ObservationIgnored internal var clipCompletedState = false

    // MARK: - Init

    override public init() {
        self.config = VoiceIOConfig()
        super.init()
        setupLoggerIfNeeded()
    }

    public init(config: VoiceIOConfig) {
        self.config = config
        super.init()
        setupLoggerIfNeeded()
    }

    private func setupLoggerIfNeeded() {
        let env = ProcessInfo.processInfo.environment
        if let logEnv = env["VOICEKIT_LOG"]?.lowercased(),
           logEnv == "1" || logEnv == "true" || logEnv == "yes" {
            self.logger = { level, msg in
                print("[VoiceKit][\(level)] \(msg)")
            }
        }
    }

    // MARK: - TTSConfigurable

    public func setVoiceProfile(_ profile: TTSVoiceProfile) { profilesByID[profile.id] = profile }
    public func getVoiceProfile(id: String) -> TTSVoiceProfile? { profilesByID[id] }
    public func setDefaultVoiceProfile(_ profile: TTSVoiceProfile) { defaultProfile = profile; profilesByID[profile.id] = profile }
    public func getDefaultVoiceProfile() -> TTSVoiceProfile? { defaultProfile }

    // Transitional convenience: prefer Tuning in new code.
    // These are not required by TTSConfigurable yet, but available on RealVoiceIO.
    public func setTuning(_ tuning: Tuning) {
        self.tuning = tuning
    }
    public func getTuning() -> Tuning { tuning }
    // MARK: - VoiceIO basics

    public func ensurePermissions() async throws {
        try await ensureSpeechAndMicPermissions()
    }
    public func configureSessionIfNeeded() async throws {
        try await configureAudioSessionIfNeeded()
    }

    public func listen(timeout: TimeInterval, inactivity: TimeInterval, record: Bool) async throws -> VoiceResult {
        log(.info, "listen(start) timeout=\(timeout), inactivity=\(inactivity), record=\(record)")
        isListening = true
        defer { isListening = false }

        // CI/headless path: keep the stub behavior so tests remain deterministic
        // and never require real hardware or permissions.
        if IsCI.running {
            if timeout > 0 {
                let nanos = UInt64(min(timeout, 0.05) * 1_000_000_000)
                if nanos > 0 { try? await Task.sleep(nanoseconds: nanos) }
            }

            // If context expects a number, synthesize a final "42"
            if recognitionContext.expectNumber {
                let ciTranscript = "42"
                log(.info, "listen(result/ci) synthesized numeric: \(ciTranscript)")
                transcript = ciTranscript
                return VoiceResult(transcript: ciTranscript, recordingURL: nil)
            }

            // Otherwise, return whatever has been set externally (default empty)
            let stub = VoiceResult(transcript: transcript, recordingURL: nil)
            log(.info, "listen(result/ci) transcript='\(stub.transcript)' record=\(record)")
            return stub
        }

        // App path: configure per-listen recording intent; the STT pipeline
        // will honor this and emit a trimmed recording URL when possible.
        currentListenShouldRecord = record
        rawRecordingURL = nil

        // App path: use the live STT pipeline defined in RealVoiceIO+STT.swift.
        let live = try await performSTTListen(timeout: timeout,
                                              inactivity: inactivity,
                                              record: record)
        log(.info, "listen(result/live) transcript='\(live.transcript)' record=\(record)")
        return live
    }

    // Called by tests; store context for listen shim
    public func setRecognitionContext(_ context: RecognitionContext) {
        self.recognitionContext = context
    }

    public func stopAll() {
        synthesizer?.stopSpeaking(at: .immediate)
    }

    /// Extend the STT inactivity timeout by marking current time as a "loud" moment.
    /// Useful when the app detects user activity (e.g., button press) and wants to prevent
    /// the listen from timing out during an intentional pause.
    /// - Parameter: unused; reserved for future API expansion (e.g., to extend by a specific duration).
    public func extendListen(by: TimeInterval? = nil) {
        let now = ProcessInfo.processInfo.systemUptime
        Task {
            await sttActivityTracker.markLoud(at: now)
        }
    }

    public func hardReset() {
        // Stop any TTS in progress.
        stopAll()

        // Tear down any in-flight STT listen.
        listenOverallTask?.cancel()
        listenOverallTask = nil
        listenInactivityTask?.cancel()
        listenInactivityTask = nil

        audioEngine?.stop()
        audioEngine?.inputNode.removeTap(onBus: 0)
        audioEngine = nil

        recognitionTask?.cancel()
        recognitionTask = nil
        recognitionRequest = nil

        // If a live listen was waiting on a continuation, resume it with
        // cancellation so callers can unwind cleanly.
        if !hasFinishedRecognition {
            hasFinishedRecognition = true
            listenCont?.resume(throwing: CancellationError())
        }
        listenCont = nil

        if let raw = rawRecordingURL {
            try? FileManager.default.removeItem(at: raw)
        }
        rawRecordingURL = nil
        currentListenShouldRecord = false
        firstSpeechStart = nil
        lastSpeechEnd = nil
        transcript = ""

        // Clear TTS bookkeeping.
        speakContinuations.removeAll()
        ttsStartTimes.removeAll()
        measureContinuations.removeAll()

        // Clear clip playback state.
        avClipPlayer?.stop()
        avClipPlayerState = nil
        clipPlayerNodeState?.stop()
        clipPlayerNodeState = nil
        clipWaitersState.removeAll()
        clipCompletedState = false
    }
}
