//
//  ScriptedVoiceIO.swift
//  VoiceKit
//
//  Generated by GPT-5 (OpenAI)
//  collaborator: rdoggett
//  date: 09-15-2025
//

import Foundation
import CoreGraphics
import Observation

@Observable
@MainActor
public final class ScriptedVoiceIO: VoiceIO {
    public var isSpeaking: Bool = false
    public var isListening: Bool = false
    public var transcript: String = ""
    public var audioLevel: CGFloat = 0
    public var pulse: CGFloat = 0
    public var statusMessage: String? = nil

    private var queue: [String]
    private var epoch: Int = 0

    // Convenience non-Base64 init for tests/demos
    public init(script: [String]) {
        self.queue = script
    }

    public init?(fromBase64 jsonBase64: String) {
        guard let data = Data(base64Encoded: jsonBase64),
              let arr = try? JSONSerialization.jsonObject(with: data) as? [String] else {
            return nil
        }
        self.queue = arr
    }

    public func ensurePermissions() async throws { }
    public func configureSessionIfNeeded() async throws { }

    public func speak(_ text: String) async {
        isSpeaking = true
        pulse = 0.35
        let steps = 6
        for stepIndex in 0..<steps {
            let phase = Double(stepIndex) / Double(steps - 1)
            let level = 0.28 + 0.24 * sin(phase * .pi)
            pulse = CGFloat(level)
            try? await Task.sleep(nanoseconds: 50_000_000)
        }
        pulse = 0.0
        isSpeaking = false
    }

    public func listen(timeout: TimeInterval, inactivity: TimeInterval, record: Bool) async throws -> VoiceResult {
        let myEpoch = epoch
        isListening = true
        audioLevel = 0.2
        try? await Task.sleep(nanoseconds: 120_000_000)
        if myEpoch != epoch {
            audioLevel = 0.0
            isListening = false
            return VoiceResult(transcript: "", recordingURL: nil)
        }
        let result = queue.isEmpty ? "" : queue.removeFirst()
        transcript = result
        try? await Task.sleep(nanoseconds: 40_000_000)
        audioLevel = 0.0
        isListening = false
        return VoiceResult(transcript: result, recordingURL: nil)
    }

    public func pause(_ seconds: TimeInterval) async {
        try? await Task.sleep(for: .seconds(seconds))
    }

    public func prepareClip(url: URL, gainDB: Float) async throws { }
    public func startPreparedClip() async throws { }
    public func playClip(url: URL, gainDB: Float) async throws { }

    public func stopAll() {
        epoch &+= 1
        isListening = false
    }

    public func hardReset() {
        epoch &+= 1
        isListening = false
        transcript = ""
        audioLevel = 0
        pulse = 0
        isSpeaking = false
        statusMessage = nil
    }
}
