//
//  TunerSliderRow.swift
//  VoiceKit
//
//  Generated by GPT-5 (OpenAI) — collaborator: rdoggett
//  date: 10-19-2025
//

import SwiftUI

/// A Voice Tuner–style slider row used across VoiceKitUI.
/// Left column: icon, title, and live value (primary color).
/// Right: a SwiftUI Slider with the standard blue accent.
public struct TunerSliderRow: View {
    public var title: String
    public var systemImage: String
    @Binding public var value: Double
    public var range: ClosedRange<Double>
    public var step: Double
    public var formatted: (Double) -> String

    public init(
        title: String,
        systemImage: String,
        value: Binding<Double>,
        range: ClosedRange<Double>,
        step: Double = 0.01,
        formatted: @escaping (Double) -> String = { $0.formatted() }
    ) {
        self.title = title
        self.systemImage = systemImage
        self._value = value
        self.range = range
        self.step = step
        self.formatted = formatted
    }

    public var body: some View {
        HStack(spacing: 10) {
            VStack(spacing: 2) {
                Image(systemName: systemImage)
                    .imageScale(.medium)
                    .font(.footnote)
                    .fontWeight(.semibold)
                    .foregroundStyle(.primary)
                Text(title)
                    .font(.footnote)
                    .foregroundStyle(.primary)
                Text(formatted(value))
                    .font(.footnote)
                    .monospacedDigit()
                    .foregroundStyle(.primary)
            }
            .frame(width: 60)

            VStack(spacing: 6) {
                Slider(value: $value, in: range, step: step)
                    .tint(.blue)
            }
        }
        .frame(maxWidth: .infinity, alignment: .leading)
    }
}

// MARK: - Previews
private struct TunerSliderRowPreviewContainer: View {
    @State private var speed: Double = 0.6
    @State private var pitch: Double = 1.1
    @State private var volume: Double = 0.9

    var body: some View {
        VStack(alignment: .leading, spacing: 14) {
            TunerSliderRow(
                title: "Speed",
                systemImage: "speedometer",
                value: $speed,
                range: 0.0...1.0,
                step: 0.01,
                formatted: { $0.asMultiplier() }
            )
            TunerSliderRow(
                title: "Pitch",
                systemImage: "waveform.path.ecg",
                value: $pitch,
                range: 0.5...2.0,
                step: 0.01,
                formatted: { $0.formatted(decimals: 2) }
            )
            TunerSliderRow(
                title: "Volume",
                systemImage: "speaker.wave.2.fill",
                value: $volume, range: 0.0...1.0)
        }
        .padding()
    }
}

internal struct TunerSliderRow_Previews: PreviewProvider {
    internal static var previews: some View {
        TunerSliderRowPreviewContainer()
            .previewDisplayName("TunerSliderRow · iPhone SE (3rd gen)")
            .previewDevice("iPhone SE (3rd generation)")
    }
}
