//
//  Clipboard.swift
//  ChorusLabApp
//
//  Simple cross‑platform helpers for setting text on the system clipboard.
//  Intended to be small, readable, and easy to reuse in other projects.
//
//  Generated by GPT-5.1 (OpenAI) - collaborator: rdoggett
//  date: 11-19-2025
//

import Foundation

#if canImport(UIKit)
import UIKit
#endif

#if canImport(AppKit)
import AppKit
#endif

/// Minimal wrapper around the system clipboard for plain text.
/// - iOS / tvOS / visionOS: uses `UIPasteboard.general`.
/// - macOS: uses `NSPasteboard.general`.
/// - Other platforms: no‑op.
enum Clipboard {

    /// Set the clipboard contents to the given string on supported platforms.
    /// - Parameter text: The text to place on the clipboard.
    static func set(_ text: String) {
        #if canImport(UIKit)
        UIPasteboard.general.string = text
        #elseif canImport(AppKit)
        let pb = NSPasteboard.general
        pb.clearContents()
        pb.setString(text, forType: .string)
        #else
        _ = text // unsupported platform: intentional no‑op
        #endif
    }
}
