//
//  VoiceChooserView.swift
//  VoiceKit
//
//  A focused UI to pick a system voice and tune its settings (rate, pitch, volume)
//  with immediate audio feedback.
//
//  Generated by GPT-5.1 (OpenAI) - collaborator: rdoggett
//  date: 11-20-2025
//

import SwiftUI
import AVFoundation
import VoiceKit

@MainActor
public struct VoiceChooserView: View {
    @StateObject private var viewModel: VoiceChooserViewModel
    private var onChoose: (() -> Void)?
    private var onCancel: (() -> Void)?
    @Binding private var selectedIDBinding: String?
    @State private var selectedID: String?
    @State private var workingProfile: TTSVoiceProfile?
    @State private var selectedIDString = ""
    @State private var sliderPreviewTask: Task<Void, Never>?
    @State private var showFullLanguagePicker = false

    private var languageSelectionBinding: Binding<String> {
        Binding(
            get: { languageFilterTag(viewModel.languageFilter) },
            set: { viewModel.languageFilter = languageFilter(fromTag: $0) }
        )
    }

    // MARK: - Initializers

    public init(tts: TTSConfigurable, store: VoiceProfilesStore,
                selectedID: Binding<String?>? = nil,
                onChoose: (() -> Void)? = nil,
                onCancel: (() -> Void)? = nil) {
        _viewModel = StateObject(wrappedValue: VoiceChooserViewModel(tts: tts, store: store, allowSystemVoices: true))
        self.onChoose = onChoose
        self.onCancel = onCancel
        self._selectedIDBinding = selectedID ?? .constant(nil)
    }

    public init(tts: TTSConfigurable,
                selectedID: Binding<String?>? = nil,
                onChoose: (() -> Void)? = nil,
                onCancel: (() -> Void)? = nil) {
        self.init(tts: tts, store: VoiceProfilesStore(), selectedID: selectedID, onChoose: onChoose, onCancel: onCancel)
    }

    // MARK: - Body

    public var body: some View {
        NavigationStack {
            VStack(spacing: 10) {
                VoiceLanguagePicker(
                    showFullLanguagePicker: $showFullLanguagePicker,
                    selection: languageSelectionBinding,
                    currentLanguageName: viewModel.currentLanguageName,
                    languageOptions: viewModel.languageOptions,
                    onSetCurrent: {
                        viewModel.languageFilter = .current
                    },
                    onExpandToAll: {
                        showFullLanguagePicker = true
                        viewModel.languageFilter = .all
                    }
                )

                voicePickerSection
                sampleButtonSection
                loadingIndicator

                if let profile = workingProfile {
                    tuningSection(profile: profile)
                } else {
                    Text("Select a voice to tune").foregroundStyle(.secondary)
                }
                Spacer()
            }
            .navigationTitle("Voice Chooser")
            .onAppear {
                viewModel.refreshAvailableVoices()
                seedSelectionFromInitialState()
            }
        }
    }

    private var voicePickerSection: some View {
        Picker("Voice", selection: $selectedIDString) {
            ForEach(viewModel.filteredVoices, id: \.id) { info in
                let name = viewModel.enhancedVoiceIDs.contains(info.id) ? "\(info.name)*" : info.name
                Text("\(name) · \(info.language)").tag(info.id)
            }
        }
        .pickerStyle(pickerStyle)
        .frame(maxHeight: pickerMaxHeight)
        .padding(.horizontal, 20)
        .onChange(of: selectedIDString) { _, newID in
            selectedID = newID.isEmpty ? nil : newID
            selectedIDBinding = selectedID
            loadWorkingProfile()
            commitChanges()
            previewSpeak(samplePhrase())
        }
    }

    private var sampleButtonSection: some View {
        HStack {
            Spacer()
            Button {
                commitChanges()
                previewSpeak(samplePhrase())
            } label: {
                Label("Sample", systemImage: "play.fill")
            }
            if let secs = viewModel.lastPreviewSeconds {
                Text(secs.display(suffix: "s"))
                    .font(.footnote)
                    .monospacedDigit()
                    .foregroundStyle(.primary)
                    .padding(.leading, 8)
            }
            Spacer()
        }
    }

    private var loadingIndicator: some View {
        Group {
            if viewModel.isLoading && viewModel.voices.isEmpty {
                ProgressView()
                    .controlSize(.small)
                    .padding(.top, -8)
            }
        }
    }

    private func tuningSection(profile: TTSVoiceProfile) -> some View {
        VStack(spacing: 14) {
            VoiceTuningControls(
                rate: Binding<Float>(
                    get: { Float(workingProfile?.rate ?? profile.rate) },
                    set: { newVal in
                        workingProfile?.rate = Double(newVal.clamped(to: 0.0...1.0))
                        scheduleSliderPreview()
                    }
                ),
                pitch: Binding<Float>(
                    get: { Float(workingProfile?.pitch ?? profile.pitch) },
                    set: { newVal in
                        workingProfile?.pitch = newVal.clamped(to: 0.5...2.0)
                        scheduleSliderPreview()
                    }
                ),
                volume: Binding<Float>(
                    get: { Float(workingProfile?.volume ?? profile.volume) },
                    set: { newVal in
                        workingProfile?.volume = newVal.clamped(to: 0.0...1.0)
                        scheduleSliderPreview()
                    }
                ),
                config: VoiceTuningConfig(
                    showVolume: true,
                    rateRange: 0.0...1.0,
                    pitchRange: 0.5...2.0,
                    volumeRange: 0.0...1.0,
                    rateStep: 0.01,
                    pitchStep: 0.01,
                    volumeStep: 0.01
                ),
                labels: .default
            )

            if onChoose != nil || onCancel != nil {
                chooserActions
            }
        }
        .padding(.horizontal, 20)
    }

    private var chooserActions: some View {
        HStack(spacing: 12) {
            if let onCancel {
                Button(role: .cancel) { onCancel() }
                label: { Text("Cancel") }
            }
            Spacer()
            if let onChoose {
                Button {
                    selectedIDBinding = selectedID
                    commitChanges()
                    onChoose()
                } label: { Text("Choose") }
                    .buttonStyle(.borderedProminent)
            }
        }
        .padding(.top, 2)
    }

    // MARK: - Picker style helpers

#if os(iOS)
    private var pickerStyle: some PickerStyle { WheelPickerStyle() }
    private var pickerMaxHeight: CGFloat? { 180 }
#else
    private var pickerStyle: some PickerStyle { DefaultPickerStyle() }
    private var pickerMaxHeight: CGFloat? { nil }
#endif
}

// MARK: - Helper methods (extracted to reduce struct body length)

extension VoiceChooserView {
    fileprivate func languageFilterTag(_ filter: VoiceChooserViewModel.LanguageFilter) -> String {
        switch filter {
        case .current: return "_current"
        case .all: return "_all"
        case .specific(let code): return code.lowercased()
        }
    }

    fileprivate func languageFilter(fromTag tag: String) -> VoiceChooserViewModel.LanguageFilter {
        switch tag {
        case "_current": return .current
        case "_all": return .all
        default: return .specific(tag.lowercased())
        }
    }

    /// Seed the initial selection from the external binding or store defaults.
    fileprivate func seedSelectionFromInitialState() {
        // 1) External binding, if valid
        if selectedID == nil,
           let bound = selectedIDBinding,
           viewModel.voices.contains(where: { $0.id == bound }) {
            selectedID = bound
        }

        // 2) Store default, if present and valid
        if selectedID == nil,
           let def = viewModel.store.defaultVoiceID,
           viewModel.voices.contains(where: { $0.id == def }) {
            selectedID = def
        }

        // 3) Fallback: first filtered voice
        if selectedID == nil {
            selectedID = viewModel.filteredVoices.first?.id
        }

        selectedIDString = selectedID ?? ""
        loadWorkingProfile()
    }

    fileprivate func loadWorkingProfile() {
        guard let id = selectedID,
              let info = viewModel.voices.first(where: { $0.id == id }) else {
            workingProfile = nil
            return
        }
        var profile = viewModel.store.profile(for: info)
        if let seeded = viewModel.store.profilesByID[id] {
            profile = seeded
        }
        if let engineProfile = viewModel.profileFromTTS(id: id) {
            profile = engineProfile
        }
        workingProfile = profile
    }

    fileprivate func commitChanges() {
        guard let profile = workingProfile else { return }
        viewModel.updateProfile(profile)
        viewModel.applyToTTS()
    }

    fileprivate func scheduleSliderPreview() {
        guard selectedID != nil, workingProfile != nil else { return }
        sliderPreviewTask?.cancel()

        sliderPreviewTask = Task { @MainActor in
            try? await Task.sleep(nanoseconds: 180_000_000)
            if Task.isCancelled { return }
            commitChanges()
            previewSpeak(samplePhrase())
        }
    }

    fileprivate func samplePhrase() -> String {
        if let profile = workingProfile {
            return viewModel.samplePhrase(for: profile)
        }
        return "The quick brown fox jumps over the lazy dog."
    }

    fileprivate func previewSpeak(_ text: String) {
        guard let id = selectedID else { return }
        viewModel.playPreview(phrase: text, voiceID: id)
    }
}

// MARK: - Preview
internal struct VoiceChooserView_Previews: PreviewProvider {
    internal static var previews: some View {
        VoiceChooserPreviewContainer()
    }
}

private struct VoiceChooserPreviewContainer: View {
    @State private var pickedVoiceID: String?
    private let tts: TTSConfigurable = RealVoiceIO()

    var body: some View {
        let chooser = VoiceChooserView(
            tts: tts,
            selectedID: $pickedVoiceID,
            onChoose: {},
            onCancel: {}
        )
        chooser
            .frame(minWidth: 375, minHeight: 520) // "SE-friendly" preview size
    }
}
