//
//  BoostedSchedulingSeamTests.swift
//  VoiceKit
//
//  Generated by GPT-5 (OpenAI) - collaborator: rdoggett
//  date: 09-20-2025
//

import XCTest
@testable import VoiceKit
import AVFoundation

@MainActor
internal final class BoostedSchedulingSeamTests: XCTestCase {

    func testClipTimeoutConfigIsRespected() async throws {
        var cfg = VoiceIOConfig()
        cfg.clipWaitTimeoutSeconds = 0.05

        let io = RealVoiceIO(config: cfg)
        XCTAssertEqual(io.config.clipWaitTimeoutSeconds, 0.05, accuracy: 0.0001)
    }

    func testResetCalledOnStopClip() async throws {
        let io = RealVoiceIO()
        // Add a waiter; it is immediately resumed by boostWaiters setter and not retained.
        try? await withCheckedThrowingContinuation { (cont: CheckedContinuation<Void, Error>) in
            var waiters = io.boostWaiters
            waiters.append(cont)
            io.boostWaiters = waiters
            // Do not assert on count; continuation is already resumed and not stored.
        }

        // Calling stopClip should be idempotent and leave no waiters.
        io.stopClip()
        XCTAssertTrue(io.boostWaiters.isEmpty)
        // A second call should also no-op.
        io.stopClip()
        XCTAssertTrue(io.boostWaiters.isEmpty)
    }
}
