//
//  CoreSanityTests.swift
//  VoiceKit
//
//  Generated by GPT-5 (OpenAI) - collaborator: rdoggett
//  date: 09-17-2025
//

import XCTest
@testable import VoiceKit

import TestSupport
@MainActor
internal final class CoreSanityTests: TestSupport.QoSNeutralizingTestCase {

    func testMakeLiveAndBasicSpeak() async throws {
        // Use VoiceIOConfig directly (no RealVoiceIO.Config)
        let io = RealVoiceIO.makeLive(config: VoiceIOConfig())

        // Minimal TTS profile (no displayName)
        let profile = TTSVoiceProfile(id: "com.apple.speech.synthesis.voice.Alex", rate: 0.55, pitch: 1.0, volume: 1.0)
        io.setDefaultVoiceProfile(profile)

        await io.speak("Sanity check.")
        // If no crash, basic path works.
    }
}
