//
//  ListenFlowSeamTests.swift
//  VoiceKit
//
//  Generated by GPT-5 (OpenAI) - collaborator: rdoggett
//  date: 09-17-2025
//

import XCTest
@testable import VoiceKit

@MainActor
internal final class RealVoiceIOListenCITests: XCTestCase {

    // These seam tests are intended to be deterministic and not depend on
    // real hardware, permissions, or AVFoundation behavior. Force CI mode
    // via VOICEKIT_FORCE_CI so RealVoiceIO.listen() uses its stub path
    // instead of the live STT pipeline.
    override func setUp() {
        super.setUp()
        setenv("VOICEKIT_FORCE_CI", "true", 1)
    }

    override func tearDown() {
        unsetenv("VOICEKIT_FORCE_CI")
        super.tearDown()
    }

    func testListenEmitsTranscriptAndFinishesOnFinal() async throws {
        let io = RealVoiceIO(config: .init())
        io.setRecognitionContext(.init(expectation: .number))

        var observedTranscripts: [String] = []
        io.onTranscriptChanged = { observedTranscripts.append($0) }

        let result = try await io.listen(timeout: 1.0, inactivity: 0.4, record: false)
        XCTAssertEqual(result.transcript, "42")
        XCTAssertTrue(observedTranscripts.contains("42"))
    }

    func testListenInactivityTimerFinishes() async throws {
        let io = RealVoiceIO(config: .init())
        let result = try await io.listen(timeout: 2.0, inactivity: 0.2, record: false)
        // In CI mode, the stub always returns a VoiceResult with a non-nil transcript
        // (possibly the empty string). This assertion simply checks that the call
        // completes and yields a value.
        XCTAssertNotNil(Optional(result.transcript))
    }
}
