//
//  PermissionBridgeTests.swift
//  VoiceKit
//
//  Generated by GPT-5 (OpenAI) — collaborator: rdoggett
//  date: 09-17-2025
//

import XCTest
@testable import VoiceKit
@preconcurrency import Speech

final class PermissionBridgeTests: XCTestCase {

    func testAwaitSpeechAuthReturnsStatus() async {
        // This should complete quickly and return a valid enum value.
        // In CI, requestAuthorization immediately invokes completion.
        let status = await PermissionBridge.awaitSpeechAuth()
        // Validate it’s one of the known cases
        switch status {
        case .authorized, .denied, .notDetermined, .restricted:
            XCTAssertTrue(true)
        @unknown default:
            XCTFail("Unknown auth status returned")
        }
    }

    func testAwaitMicPermissionReturnsBool() async {
        let granted = await PermissionBridge.awaitMicPermission()
        // Just assert we got a boolean quickly; don’t depend on true/false in CI.
        XCTAssertNotNil(Optional(granted))
    }
}
