//
//  RealVoiceIOTTSTests.swift
//  VoiceKit
//
//  Generated by GPT-5 (OpenAI) - collaborator: rdoggett
//  date: 09-17-2025
//

import XCTest
@testable import VoiceKit
import TestSupport

@MainActor
internal final class RealVoiceIOTTSTests: TestSupport.QoSNeutralizingTestCase {

    func testApplyProfileAndSpeak() async throws {
        let io = RealVoiceIO()

        // No displayName in TTSVoiceProfile
        let alex = TTSVoiceProfile(id: "com.apple.speech.synthesis.voice.Alex", rate: 0.6, pitch: 1.05, volume: 1.0)
        io.setVoiceProfile(alex)
        io.setDefaultVoiceProfile(alex)

        // Tuning initializer order: rateVariation, pitchVariation, volume
        io.setTuning(Tuning(rateVariation: 0.01, pitchVariation: 0.02, volume: 0.9))

        await io.speak("Applying profile for test.")
        // If no crash, mapping succeeded.
    }

    func testSpeakContinuationsCleanedUpAfterRepetitions() async throws {
        let io = RealVoiceIO()

        // Set fast rate (0.85) and quiet volume for test tolerance
        let fastProfile = TTSVoiceProfile(id: "com.apple.speech.synthesis.voice.Alex", rate: 0.85, pitch: 1.0, volume: 0.2)
        io.setVoiceProfile(fastProfile)
        io.setDefaultVoiceProfile(fastProfile)
        io.setTuning(Tuning(rateVariation: 0.01, pitchVariation: 0.02, volume: 0.2))

        // Perform short speak operations to verify continuations are cleaned up.
        let syllables = ["A", "B", "C", "D", "E"]

        for i in 0..<20 {
            let syll = syllables[i % syllables.count]
            await io.speak(syll)
        }

        // Verify continuation dictionaries are empty (not leaking).
        // This verifies the speak operations actually completed (continuations resumed and cleaned up).
        XCTAssertTrue(io.speakContinuations.isEmpty, "speakContinuations should be empty after all speaks complete")
        XCTAssertTrue(io.ttsStartTimes.isEmpty, "ttsStartTimes should be empty after all speaks complete")
        XCTAssertTrue(io.measureContinuations.isEmpty, "measureContinuations should be empty after all speaks complete")
    }

    /// Regression test for the unsafeForcedSync / mBuffers zero-byte bug.
    ///
    /// Root cause: AVSpeechSynthesizer.speak() internally calls dispatch_sync-style
    /// primitives that AVFoundation flags as unsafe when called from a Swift Task
    /// context. This corrupts audio-buffer setup, causing every buffer to arrive
    /// with mDataByteSize == 0.  The symptom is that speakAndMeasure() returns 0
    /// duration for every utterance even though didStart/didFinish still fire.
    ///
    /// Fix: dispatch speak() via DispatchQueue.main.async so it runs in a plain GCD
    /// block that Swift's concurrency runtime does not tag as a concurrent context.
    ///
    /// Note: the warning itself prints to the console and cannot be captured by
    /// XCTest assertions. We instead assert on the behavioral symptom: each
    /// utterance must produce a measurably non-zero audio duration.
    func testSpeakFromAsyncContextProducesNonZeroAudioDuration() async throws {
        guard !IsCI.running else { throw XCTSkip("Real TTS path; skipped in CI.") }

        let io = RealVoiceIO()
        let profile = TTSVoiceProfile(
            id: "com.apple.speech.synthesis.voice.Alex",
            rate: 0.85, pitch: 1.0, volume: 0.1
        )
        io.setDefaultVoiceProfile(profile)

        // Each sentence must have measurable duration. Zero would indicate the
        // audio-buffer corruption introduced by calling speak() inside a Swift Task.
        let phrases = ["Testing one.", "Testing two.", "Testing three."]
        for phrase in phrases {
            let duration = await io.speakAndMeasure(phrase, using: nil)
            XCTAssertGreaterThan(
                duration, 0.05,
                "'\(phrase)' produced zero-duration audio — likely mBuffers[0].mDataByteSize == 0 regression"
            )
        }
    }

    /// Regression: first speak on a fresh instance must not trigger unsafeForcedSync.
    ///
    /// Root cause: AVSpeechSynthesizer() internally calls AFPreferences via dispatch_sync.
    /// When this happens inside a Swift Task context (even @MainActor), the runtime tags
    /// the call as unsafeForcedSync, which corrupts audio buffer setup — all subsequent
    /// buffers arrive with mDataByteSize == 0, silencing speech.
    ///
    /// Fix: ensureSynth() now creates the synthesizer via DispatchQueue.main.async so
    /// it runs outside the Swift task-context tag.
    func testFirstSpeakFromFreshInstanceProducesNonZeroAudioDuration() async throws {
        guard !IsCI.running else { throw XCTSkip("Real TTS path; skipped in CI.") }

        // Fresh instance — synthesizer is nil and must be created on first speak.
        let io = RealVoiceIO()
        let profile = TTSVoiceProfile(
            id: "com.apple.speech.synthesis.voice.Alex",
            rate: 0.85, pitch: 1.0, volume: 0.1
        )
        io.setDefaultVoiceProfile(profile)

        // The very first call creates AVSpeechSynthesizer; it must produce non-zero
        // duration proving the audio pipeline was not corrupted by unsafeForcedSync.
        let duration = await io.speakAndMeasure("Hello.", using: nil)
        XCTAssertGreaterThan(duration, 0.05,
            "First speak produced zero-duration audio — mBuffers regression (ensureSynth inside Swift Task context)"
        )
    }

    func testSpeakAndMeasureContinuationsCleanedUp() async throws {
        // speakAndMeasure returns 0 in CI (no AVSpeech); duration assertions require real TTS.
        guard !IsCI.running else { throw XCTSkip("Real TTS measurement; skipped in CI.") }

        let io = RealVoiceIO()

        // Set fast rate and quiet volume
        let fastProfile = TTSVoiceProfile(id: "com.apple.speech.synthesis.voice.Alex", rate: 0.85, pitch: 1.0, volume: 0.2)
        io.setVoiceProfile(fastProfile)
        io.setDefaultVoiceProfile(fastProfile)
        io.setTuning(Tuning(rateVariation: 0.01, pitchVariation: 0.02, volume: 0.2))

        // Perform short measure operations and verify cleanup.
        let syllables = ["Do", "Re", "Mi", "Fa", "Sol"]
        var totalDuration: TimeInterval = 0

        for i in 0..<15 {
            let syll = syllables[i % syllables.count]
            let duration = await io.speakAndMeasure(syll, using: nil)
            // Duration should be > 0 in the real TTS path; CI stub returns 0.
            XCTAssertGreaterThan(duration, 0, "speakAndMeasure should return non-zero duration in real TTS path")
            totalDuration += duration
        }

        // Verify we accumulated some real synthesis time across operations
        XCTAssertGreaterThan(totalDuration, 0.5, "Total synthesis time should be substantial (> 0.5s for 15 utterances)")

        // Verify all tracking dicts are empty (operations completed and cleaned up)
        XCTAssertTrue(io.speakContinuations.isEmpty, "speakContinuations should be cleaned up")
        XCTAssertTrue(io.ttsStartTimes.isEmpty, "ttsStartTimes should be cleaned up")
        XCTAssertTrue(io.measureContinuations.isEmpty, "measureContinuations should be cleaned up")
    }
}
