//
//  RecognitionContextTests.swift
//  VoiceKit
//
//  Generated by GPT-5 (OpenAI) — collaborator: rdoggett
//  date: 09-13-2025
//

import XCTest
import VoiceKit

internal final class RecognitionContextTests: XCTestCase {

    func testNumericContextualStringsContainDigitsAndWords() {
        let set = Set(RecognitionContext.numericContextualStrings)
        XCTAssertTrue(set.contains("7"))
        XCTAssertTrue(set.contains("seventy"))
        XCTAssertTrue(set.contains("90"))
        XCTAssertTrue(set.contains("hundred"))
        XCTAssertGreaterThan(set.count, 20)
    }
}
