//
//  SystemVoicesCacheTests.swift
//  VoiceKit
//
//  Regression tests for SystemVoicesCache.
//  Captures the double-speechVoices() call bug where refreshAvailableVoices()
//  used to call AVSpeechSynthesisVoice.speechVoices() a second time to filter
//  enhanced voices, producing two "Error fetching voices" console entries on
//  iOS 26 simulator (where Apple's internal voice-DB decoder falls back with a log).
//
//  Generated by Claude Sonnet 4.6 (Anthropic) — collaborator: rdoggett
//  date: 04-19-2026
//

import XCTest
@testable import VoiceKit

@MainActor
internal final class SystemVoicesCacheTests: XCTestCase {

    override func tearDown() {
        // Restore clean state so tests don't leak into each other.
        SystemVoicesCache.clear()
        super.tearDown()
    }

    // MARK: - Core cache behavior

    /// After refresh(), all() returns the same snapshot without re-querying AVFoundation.
    func testAllReturnsRefreshedSnapshot() {
        let fromRefresh = SystemVoicesCache.refresh()
        let fromAll = SystemVoicesCache.all()
        XCTAssertEqual(fromRefresh.map(\.id), fromAll.map(\.id),
                       "all() must return the same snapshot built by refresh()")
    }

    /// enhancedVoiceIDs() returns a subset of all voice IDs — never IDs for unknown voices.
    func testEnhancedIDsAreSubsetOfAllIDs() {
        _ = SystemVoicesCache.refresh()
        let allIDs = Set(SystemVoicesCache.all().map(\.id))
        let enhanced = SystemVoicesCache.enhancedVoiceIDs()
        XCTAssertTrue(enhanced.isSubset(of: allIDs),
                      "enhancedVoiceIDs() must only contain IDs present in all()")
    }

    /// Multiple calls to enhancedVoiceIDs() without re-refreshing return identical results.
    /// This is the contract that eliminates the second speechVoices() call.
    func testEnhancedIDsStableWithoutRefresh() {
        _ = SystemVoicesCache.refresh()
        let first = SystemVoicesCache.enhancedVoiceIDs()
        let second = SystemVoicesCache.enhancedVoiceIDs()
        XCTAssertEqual(first, second,
                       "enhancedVoiceIDs() must be stable across calls without a refresh()")
    }

    /// clear() resets both the voice list and the enhanced-ID set.
    func testClearResetsEnhancedIDs() {
        _ = SystemVoicesCache.refresh()
        let beforeClear = SystemVoicesCache.enhancedVoiceIDs()
        SystemVoicesCache.clear()
        // After clear the cache is empty; enhancedVoiceIDs() triggers a rebuild.
        let afterClear = SystemVoicesCache.enhancedVoiceIDs()
        // Post-rebuild should be consistent with the rebuilt voice list.
        let allIDs = Set(SystemVoicesCache.all().map(\.id))
        XCTAssertTrue(afterClear.isSubset(of: allIDs),
                      "After clear + rebuild, enhancedVoiceIDs() must still be a subset of all()")
        // Re-express the same set (both builds from same source, so they must agree).
        XCTAssertEqual(beforeClear, afterClear,
                       "clear() and re-refresh must produce the same enhanced-ID set")
    }

    /// enhancedVoiceIDs() without a prior refresh() triggers an implicit rebuild
    /// and returns a valid (possibly empty) set rather than crashing.
    func testEnhancedIDsWithoutExplicitRefreshDoesNotCrash() {
        // Cache already cleared in tearDown of prior test; clear again to be explicit.
        SystemVoicesCache.clear()
        let enhanced = SystemVoicesCache.enhancedVoiceIDs()
        // Just require it returns a valid value (may be empty in CI).
        XCTAssertNotNil(Optional(enhanced))
    }

    /// lastRefreshedAt() reflects the time of the most recent refresh().
    func testLastRefreshedAtUpdatesAfterRefresh() throws {
        let before = Date()
        _ = SystemVoicesCache.refresh()
        let stamp = try XCTUnwrap(SystemVoicesCache.lastRefreshedAt(),
                                  "lastRefreshedAt() must be non-nil after refresh()")
        XCTAssertGreaterThanOrEqual(stamp.timeIntervalSince(before), 0,
                                    "lastRefreshedAt() must be >= the time refresh() was called")
    }
}
