//
//  VoiceKitTestModeHarness.swift
//  VoiceKit
//
//  Generated by GPT-5 (OpenAI) - collaborator: rdoggett
//  date: 09-17-2025
//

import XCTest
@testable import VoiceKit

@MainActor
internal final class VoiceKitTestModeHarness: XCTestCase {

    override func setUp() {
        super.setUp()
        Task { await VoiceKitTestMode.setAllowSystemVoiceQueries(false) }
    }

    override func tearDown() {
        Task { await VoiceKitTestMode.setAllowSystemVoiceQueries(false) }
        super.tearDown()
    }
}
