//
//  VoiceTempoCalibrationTests.swift
//  VoiceKit
//
//  Tests for VoiceTempoCalibrator iterative rate calibration algorithm.
//  Covers convergence, cancellation, zero-measurement safety, early exit conditions.
//
//  Generated by Claude Haiku 4.5 (Anthropic) — collaborator: rdoggett
//  date: 03-09-2026
//

import XCTest
@testable import VoiceKit

@MainActor
internal final class VoiceTempoCalibrationTests: XCTestCase {

    func testConvergesWhenMeasurementApproachesTarget() async {
        let voiceID = "test.voice.one"
        let target = 2.0
        let tolerance = 0.05

        // Simulate sequence of measurements that converge: 3.0 → 2.2 → 2.05
        // Each rate adjustment proportional to ratio of measured/target
        let measurements: [TimeInterval] = [3.0, 2.2, 2.05]
        let fake = FakeVoiceIOForCalibration(measurements: measurements)

        var iterations: [FakeVoiceIOForCalibration.IterationRecord] = []
        let result = await VoiceTempoCalibrator.fitRate(
            io: fake,
            voiceID: voiceID,
            phrase: "Test",
            targetSeconds: target,
            tolerance: tolerance,
            maxIterations: 5,
            onIteration: { idx, measured, next in
                iterations.append(FakeVoiceIOForCalibration.IterationRecord(index: idx, measuredSeconds: measured, nextRate: next))
            }
        )

        // Should converge within tolerance (2.05 vs 2.0 = 0.05 delta)
        XCTAssertEqual(result.measured, 2.05, accuracy: 0.01)
        XCTAssertGreaterThan(iterations.count, 0)
        // Should have stopped early due to tolerance, not max iterations
        XCTAssertLessThan(iterations.count, 5)
    }

    func testZeroMeasurementSafety() async {
        let voiceID = "test.voice.two"
        let target = 1.5
        let measurements: [TimeInterval] = [0.0]
        let fake = FakeVoiceIOForCalibration(measurements: measurements)

        var iterations: [FakeVoiceIOForCalibration.IterationRecord] = []
        let result = await VoiceTempoCalibrator.fitRate(
            io: fake,
            voiceID: voiceID,
            phrase: "Test",
            targetSeconds: target,
            tolerance: 0.05,
            maxIterations: 3,
            onIteration: { idx, measured, next in
                iterations.append(FakeVoiceIOForCalibration.IterationRecord(index: idx, measuredSeconds: measured, nextRate: next))
            }
        )

        // Zero measurement should trigger early exit after first iteration
        XCTAssertEqual(result.measured, 0.0)
        XCTAssertEqual(iterations.count, 1)
        XCTAssertEqual(iterations[0].measuredSeconds, 0.0)
    }

    func testCancellationDetection() async {
        // Verify the algorithm checks Task.isCancelled before proceeding
        let task = Task { @MainActor in
            for _ in 0..<5 where Task.isCancelled {
                return true
            }
            return false
        }

        task.cancel()
        let wasChecked = await task.value

        XCTAssertTrue(wasChecked)
    }

    func testNegativeMeasurementTreatedAsZero() async {
        let voiceID = "test.voice.four"
        let target = 1.0
        let measurements: [TimeInterval] = [-0.1]
        let fake = FakeVoiceIOForCalibration(measurements: measurements)

        var iterations: [FakeVoiceIOForCalibration.IterationRecord] = []
        let result = await VoiceTempoCalibrator.fitRate(
            io: fake,
            voiceID: voiceID,
            phrase: "Test",
            targetSeconds: target,
            tolerance: 0.05,
            maxIterations: 3,
            onIteration: { idx, measured, next in
                iterations.append(FakeVoiceIOForCalibration.IterationRecord(index: idx, measuredSeconds: measured, nextRate: next))
            }
        )

        // Negative measurement <= 0 should trigger early exit
        XCTAssertLessThanOrEqual(result.measured, 0.0)
        XCTAssertEqual(iterations.count, 1)
    }

    func testNegligibleChangeStopsEarly() async {
        let voiceID = "test.voice.five"
        let target = 1.0
        // Measurement very close to target, so update will be negligible (< 0.001)
        let measurements: [TimeInterval] = [1.0001]
        let fake = FakeVoiceIOForCalibration(measurements: measurements)

        var iterations: [FakeVoiceIOForCalibration.IterationRecord] = []
        _ = await VoiceTempoCalibrator.fitRate(
            io: fake,
            voiceID: voiceID,
            phrase: "Test",
            targetSeconds: target,
            tolerance: 0.05,
            maxIterations: 3,
            onIteration: { idx, measured, next in
                iterations.append(FakeVoiceIOForCalibration.IterationRecord(index: idx, measuredSeconds: measured, nextRate: next))
            }
        )

        // Should exit on first iteration due to negligible change (measured rate * (1.0001 / 1.0) ≈ negligible delta)
        XCTAssertEqual(iterations.count, 1)
    }
}

// MARK: - Additional Tests

extension VoiceTempoCalibrationTests {
    func testBoundsClamping() async {
        let voiceID = "test.voice.six"
        let target = 2.0
        let bounds = 0.2...0.8 as ClosedRange<Double>
        // Start with high measurement → rate should clamp to upper bound
        let measurements: [TimeInterval] = [5.0, 4.0, 3.0]
        let fake = FakeVoiceIOForCalibration(measurements: measurements)

        var iterations: [FakeVoiceIOForCalibration.IterationRecord] = []
        let result = await VoiceTempoCalibrator.fitRate(
            io: fake,
            voiceID: voiceID,
            phrase: "Test",
            targetSeconds: target,
            tolerance: 0.05,
            maxIterations: 5,
            bounds: bounds,
            onIteration: { idx, measured, next in
                iterations.append(FakeVoiceIOForCalibration.IterationRecord(index: idx, measuredSeconds: measured, nextRate: next))
            }
        )

        // Final rate should be within bounds
        XCTAssertGreaterThanOrEqual(result.finalRate, bounds.lowerBound)
        XCTAssertLessThanOrEqual(result.finalRate, bounds.upperBound)
    }

    func testMaxIterationsRespected() async {
        let voiceID = "test.voice.seven"
        let target = 2.0
        let maxIter = 2
        // Provide way more measurements than maxIterations
        let measurements = (0..<10).map { _ in TimeInterval.random(in: 1.5...2.5) }
        let fake = FakeVoiceIOForCalibration(measurements: measurements)

        var iterations: [FakeVoiceIOForCalibration.IterationRecord] = []
        _ = await VoiceTempoCalibrator.fitRate(
            io: fake,
            voiceID: voiceID,
            phrase: "Test",
            targetSeconds: target,
            tolerance: 0.001, // high tolerance to prevent early exit
            maxIterations: maxIter,
            onIteration: { idx, measured, next in
                iterations.append(FakeVoiceIOForCalibration.IterationRecord(index: idx, measuredSeconds: measured, nextRate: next))
            }
        )

        // Should stop at maxIterations
        XCTAssertLessThanOrEqual(iterations.count, maxIter)
    }

    func testUsesDefaultProfileRateIfNoneExists() async {
        let voiceID = "test.voice.eight"
        let target = 1.0
        let defaultRate = 0.6
        let measurements: [TimeInterval] = [1.5]
        let fake = FakeVoiceIOForCalibration(measurements: measurements)

        // Set default profile (no explicit profile for voiceID yet)
        fake.setDefaultVoiceProfile(TTSVoiceProfile(id: "default", rate: defaultRate, pitch: 1.0, volume: 1.0))

        var iterations: [FakeVoiceIOForCalibration.IterationRecord] = []
        let result = await VoiceTempoCalibrator.fitRate(
            io: fake,
            voiceID: voiceID,
            phrase: "Test",
            targetSeconds: target,
            tolerance: 0.05,
            maxIterations: 1,
            onIteration: { idx, measured, next in
                iterations.append(FakeVoiceIOForCalibration.IterationRecord(index: idx, measuredSeconds: measured, nextRate: next))
            }
        )

        // Should have created a profile starting from default rate and adjusted it
        // First iteration: measurement 1.5 vs target 1.0 → new rate = 0.6 * (1.5 / 1.0) = 0.9
        let profile = fake.getVoiceProfile(id: voiceID)
        XCTAssertNotNil(profile)
        if let profile {
            XCTAssertEqual(profile.rate, 0.9, accuracy: 0.01)
        }
        // Verify it started from default and then adjusted
        XCTAssertGreaterThan(result.finalRate, defaultRate)
    }

    func testCallbackProgressTracking() async {
        let voiceID = "test.voice.nine"
        let target = 1.0
        let measurements: [TimeInterval] = [1.5, 1.1, 1.0]
        let fake = FakeVoiceIOForCalibration(measurements: measurements)

        var iterations: [FakeVoiceIOForCalibration.IterationRecord] = []
        _ = await VoiceTempoCalibrator.fitRate(
            io: fake,
            voiceID: voiceID,
            phrase: "Test",
            targetSeconds: target,
            tolerance: 0.05,
            maxIterations: 5,
            onIteration: { idx, measured, next in
                iterations.append(FakeVoiceIOForCalibration.IterationRecord(index: idx, measuredSeconds: measured, nextRate: next))
            }
        )

        // Should have iteration reports
        XCTAssertGreaterThan(iterations.count, 0)
        // Each report should have increasing iteration index
        for (i, report) in iterations.enumerated() where report.index == i {
            XCTAssertEqual(report.index, i)
        }
    }

    func testProportionalRateAdjustment() async {
        let voiceID = "test.voice.ten"
        let startRate = 0.5
        let target = 2.0
        let firstMeasurement = 4.0 // 2x target
        let measurements: [TimeInterval] = [firstMeasurement]
        let fake = FakeVoiceIOForCalibration(measurements: measurements)

        // Create profile with known starting rate
        let profile = TTSVoiceProfile(id: voiceID, rate: startRate, pitch: 1.0, volume: 1.0)
        fake.setVoiceProfile(profile)

        let result = await VoiceTempoCalibrator.fitRate(
            io: fake,
            voiceID: voiceID,
            phrase: "Test",
            targetSeconds: target,
            tolerance: 0.05,
            maxIterations: 1
        )

        // nextRate = startRate * (firstMeasurement / target)
        // = 0.5 * (4.0 / 2.0) = 0.5 * 2.0 = 1.0
        // But then clamped to bounds [0...1], so should be 1.0
        let expectedRate = startRate * (firstMeasurement / target)
        XCTAssertEqual(result.finalRate, min(1.0, expectedRate), accuracy: 0.01)
    }
}

// MARK: - Test Fake

@MainActor
extension VoiceTempoCalibrationTests {
    /// Minimal fake conforming to TempoMeasurable for calibration testing
    final class FakeVoiceIOForCalibration: TempoMeasurable {
        // Tracks iteration progress
        struct IterationRecord {
            let index: Int
            let measuredSeconds: TimeInterval
            let nextRate: Double
        }

        private var measurements: [TimeInterval]
        private var measurementIndex = 0
        private(set) var stopAllWasCalled = false
        private(set) var profiles: [String: TTSVoiceProfile] = [:]
        private(set) var defaultProfile: TTSVoiceProfile?

        init(measurements: [TimeInterval]) {
            self.measurements = measurements
        }

        // MARK: - TTSConfigurable

        func setVoiceProfile(_ profile: TTSVoiceProfile) { profiles[profile.id] = profile }
        func getVoiceProfile(id: String) -> TTSVoiceProfile? { profiles[id] }
        func setDefaultVoiceProfile(_ profile: TTSVoiceProfile) { defaultProfile = profile; profiles[profile.id] = profile }
        func getDefaultVoiceProfile() -> TTSVoiceProfile? { defaultProfile }
        func setTuning(_ tuning: Tuning) {}
        func getTuning() -> Tuning { .init() }
        func speak(_ text: String, using voiceID: String?) async {}

        // MARK: - TempoMeasurable

        func speakAndMeasure(_ text: String, using voiceID: String?) async -> TimeInterval {
            let result = measurementIndex < measurements.count ? measurements[measurementIndex] : 0.0
            measurementIndex += 1
            return result
        }

        func stopAll() { stopAllWasCalled = true }
    }
}
