//
//  VoiceKitInfo.swift
//  VoiceKitCore
//
//  Generated by GPT-5 (OpenAI) — collaborator: rdoggett
//  date: 09-16-2025
//

import Foundation

public enum VoiceKitInfo {
    // Bump this when you tag a new release
    public static let version = "0.1.1"

    public static var buildTimestampISO8601: String {
        ISO8601DateFormatter().string(from: Date())
    }
}
