//
//  PermissionBridge.swift
//  VoiceKit
//
//  Generated by GPT-5 (OpenAI)
//  collaborator: rdoggett
//  date: 09-16-2025
//

import Foundation
@preconcurrency import Speech
@preconcurrency import AVFoundation

enum PermissionBridge {

    nonisolated static func awaitSpeechAuth() async -> SFSpeechRecognizerAuthorizationStatus {
        // In CI, avoid system prompts that can hang headless runners.
        if IsCI.running { return .authorized }
        return await withCheckedContinuation { (continuation: CheckedContinuation<SFSpeechRecognizerAuthorizationStatus, Never>) in
            SFSpeechRecognizer.requestAuthorization { status in
                continuation.resume(returning: status)
            }
        }
    }

    nonisolated static func awaitMicPermission() async -> Bool {
        if IsCI.running { return true }
        return await withCheckedContinuation { (cont: CheckedContinuation<Bool, Never>) in
            #if os(iOS)
            AVAudioApplication.requestRecordPermission { cont.resume(returning: $0) }
            #elseif os(macOS)
            AVCaptureDevice.requestAccess(for: .audio) { cont.resume(returning: $0) }
            #else
            cont.resume(returning: true)
            #endif
        }
    }
}
