//
//  PermissionBridge.swift
//  VoiceKit
//
//  Generated by GPT-5 (OpenAI)
//  collaborator: rdoggett
//  date: 09-16-2025
//

import Foundation
@preconcurrency import Speech
@preconcurrency import AVFoundation

enum PermissionBridge {

    nonisolated static func awaitSpeechAuth() async -> SFSpeechRecognizerAuthorizationStatus {
        // In CI, avoid system prompts that can hang headless runners.
        if IsCI.running {
            return .authorized
        }
        return await withCheckedContinuation { (continuation: CheckedContinuation<SFSpeechRecognizerAuthorizationStatus, Never>) in
            SFSpeechRecognizer.requestAuthorization { status in
                continuation.resume(returning: status)
            }
        }
    }

    #if os(iOS)
    nonisolated static func awaitMicPermission() async -> Bool {
        if IsCI.running {
            return true
        }
        return await withCheckedContinuation { (continuation: CheckedContinuation<Bool, Never>) in
            AVAudioApplication.requestRecordPermission { granted in
                continuation.resume(returning: granted)
            }
        }
    }
    #elseif os(macOS)
    nonisolated static func awaitMicPermission() async -> Bool {
        if IsCI.running {
            return true
        }
        return await withCheckedContinuation { (continuation: CheckedContinuation<Bool, Never>) in
            AVCaptureDevice.requestAccess(for: .audio) { granted in
                continuation.resume(returning: granted)
            }
        }
    }
    #endif
}
