//
//  RealVoiceIO+STT.swift
//  VoiceKit
//
//  Live STT pipeline for RealVoiceIO.
//  - In CI/headless (IsCI.running): RealVoiceIO.listen() stays on its stub path.
//  - In apps: RealVoiceIO.listen() calls performSTTListen(..) to drive AVAudioEngine + SFSpeechRecognizer.
//
//  Generated by GPT-5.1 (OpenAI) - collaborator: rdoggett
//  date: 11-23-2025
//

import Foundation
@preconcurrency import AVFoundation
@preconcurrency import Speech
import Accelerate
import CoreGraphics

@MainActor
extension RealVoiceIO {

    // MARK: - Legacy test hook

    /// Legacy no-op used by older tests to simulate end-of-speech.
    ///
    /// The modern live STT pipeline does **not** depend on this hook; it
    /// completes listens via recognizer callbacks, inactivity timers, and
    /// overall timeouts. The method remains only to avoid breaking existing
    /// callers and can be treated as a harmless stub in new code.
    public func finishRecognition() {
        // no-op stub; present for legacy test compatibility
    }

    // MARK: - Live STT implementation (app path)

    /// Ensure mic + speech permissions are granted; throws on failure.
    ///
    /// - Behavior:
    ///   - On devices and simulators (normal app runs), this:
    ///     - Requests microphone access using the appropriate API per platform.
    ///     - Awaits speech recognizer authorization via `PermissionBridge`.
    ///     - Verifies that the `SFSpeechRecognizer` is currently available.
    ///   - Under CI or forced test mode (`IsCI.running == true` / `VOICEKIT_FORCE_CI`):
    ///     - `PermissionBridge` helpers short-circuit and return "granted"
    ///       to keep headless tests deterministic and free of TCC prompts.
    internal func ensureSpeechAndMicPermissions() async throws {
        // Short-circuit in CI/headless; tests never hit real STT.
        if IsCI.running { return }

        let micOK: Bool
        #if os(iOS)
        if #available(iOS 17.0, *) {
            micOK = await withCheckedContinuation { (continuation: CheckedContinuation<Bool, Never>) in
                AVAudioApplication.requestRecordPermission { continuation.resume(returning: $0) }
            }
        } else {
            micOK = await withCheckedContinuation { (continuation: CheckedContinuation<Bool, Never>) in
                AVAudioSession.sharedInstance().requestRecordPermission { continuation.resume(returning: $0) }
            }
        }
        #elseif os(macOS)
        micOK = await withCheckedContinuation { (continuation: CheckedContinuation<Bool, Never>) in
            AVCaptureDevice.requestAccess(for: .audio) { continuation.resume(returning: $0) }
        }
        #else
        micOK = false
        #endif

        guard micOK else { throw VoiceIOError.micUnavailable }

        // Speech permission
        let status = await PermissionBridge.awaitSpeechAuth()
        guard status == .authorized else { throw VoiceIOError.micUnavailable }
        if speechRecognizer == nil {
            speechRecognizer = SFSpeechRecognizer(locale: .autoupdatingCurrent)
        }
        guard speechRecognizer?.isAvailable == true else { throw VoiceIOError.recognizerUnavailable }
    }

    /// Configure audio session for voice I/O where applicable.
    internal func configureAudioSessionIfNeeded() async throws {
        #if os(iOS)
        let session = AVAudioSession.sharedInstance()
        try? session.setActive(false, options: [])
        var opts: AVAudioSession.CategoryOptions = [.defaultToSpeaker, .duckOthers]
        opts.insert(.allowBluetoothHFP)
        try session.setCategory(.playAndRecord, mode: .voiceChat, options: opts)
        try session.setPreferredSampleRate(44100)
        try session.setPreferredIOBufferDuration(0.01)
        try session.setActive(true, options: [])
        #else
        // macOS: rely on default session.
        _ = ()
        #endif
    }

    /// Install an AVAudioEngine input tap that forwards audio buffers into the
    /// given SFSpeechAudioBufferRecognitionRequest.
    ///
    /// This helper is explicitly nonisolated so the tap closure does **not**
    /// inherit @MainActor isolation. AVFoundation invokes the closure on a
    /// realtime audio queue (e.g., RealtimeMessenger.mServiceQueue); if it were
    /// @MainActor-isolated, Swift 6 would trap with `_swift_task_checkIsolatedSwift`.
    ///
    /// The activityTracker is updated from the realtime audio queue based on
    /// buffer energy and later consulted by the inactivity timer to decide
    /// when the user has gone quiet. Updates are rate-limited to ~50ms intervals
    /// to avoid task proliferation (each buffer = ~20-30ms at standard rates).
    nonisolated internal static func installRecognitionTap(
        engine: AVAudioEngine,
        request: SFSpeechAudioBufferRecognitionRequest,
        recordingFile: AVAudioFile?,
        activityTracker: STTActivityTracker
    ) throws {
        let inputNode = engine.inputNode
        let format = inputNode.inputFormat(forBus: 0)
        var lastActivityUpdateTime: TimeInterval = 0
        inputNode.installTap(onBus: 0, bufferSize: 1024, format: format) { buffer, _ in
            let frames = Int(buffer.frameLength)
            guard frames > 0 else { return }
            // Feed STT only; never touch @MainActor state from this queue.
            request.append(buffer)
            // Optionally mirror into a raw recording file. Any error here should
            // not break recognition; ignore failures.
            if let file = recordingFile {
                try? file.write(from: buffer)
            }

            // Approximate loudness in dB for this buffer and feed it into the
            // activity tracker so it can adapt to ambient noise and mark
            // "loud enough" buffers as speech activity.
            // Rate-limit updates to ~50ms intervals to prevent task explosion
            // (at 44.1kHz with 1024-sample buffers, we see ~43 buffers/sec).
            if let ch = buffer.floatChannelData?.pointee {
                var ms: Float = 0
                vDSP_measqv(ch, 1, &ms, vDSP_Length(buffer.frameLength))
                let db: Float = ms <= 0 ? -160 : 10 * log10f(ms)
                let now = ProcessInfo.processInfo.systemUptime
                if now - lastActivityUpdateTime >= 0.05 {
                    lastActivityUpdateTime = now
                    Task.detached {
                        await activityTracker.observe(db: db, at: now)
                    }
                }
            }
        }
    }

    /// Real STT listen implementation used when not in CI.
    internal func performSTTListen(timeout: TimeInterval,
                                   inactivity: TimeInterval,
                                   record: Bool) async throws -> VoiceResult {
        if speechRecognizer == nil {
            speechRecognizer = SFSpeechRecognizer(locale: .autoupdatingCurrent)
        }
        if Task.isCancelled { throw CancellationError() }

        #if os(iOS)
        if !AVAudioSession.sharedInstance().isInputAvailable {
            throw VoiceIOError.micUnavailable
        }
        #endif

        resetListenState()
        await sttActivityTracker.reset(now: ProcessInfo.processInfo.systemUptime)

        let engine = AVAudioEngine()
        audioEngine = engine

        let (request, recognizer) = try prepareRecognitionRequest()

        let inputNode = engine.inputNode
        let inputFormat = inputNode.inputFormat(forBus: 0)
        if inputFormat.channelCount == 0 || inputFormat.sampleRate <= 0 {
            throw VoiceIOError.audioFormatInvalid
        }

        let recordingFile = makeRecordingFileIfNeeded(for: inputFormat, record: record)

        // The tap itself must not be @MainActor-isolated; install it via a
        // nonisolated helper so the closure can run safely on the realtime queue.
        try Self.installRecognitionTap(
            engine: engine,
            request: request,
            recordingFile: recordingFile,
            activityTracker: sttActivityTracker
        )

        engine.prepare()
        try engine.start()

        // Tiny startup delay to avoid treating engine warm-up as inactivity.
        if timeout > 0 {
            try await Task.sleep(nanoseconds: 50_000_000)
        }
        if Task.isCancelled { throw CancellationError() }

        let expectation = recognitionContext.expectation

        log(.info, "listen(stt) recognition task starting")
        recognitionTask = recognizer.recognitionTask(
            with: request
        ) { [weak self] (result: SFSpeechRecognitionResult?, error: Error?) in
            guard let self else { return }
            if let result {
                self.handleRecognitionSuccess(
                    result: result,
                    expectation: expectation,
                    inactivity: inactivity
                )
            }
            if error != nil {
                Task { @MainActor in
                    self.log(.warn, "listen(stt) complete via recognizer error: \(error!)")
                    self.completeCurrentListen()
                }
            }
        }

        startOverallTimer(seconds: timeout)

        let result: VoiceResult = try await withCheckedThrowingContinuation { cont in
            self.listenCont = cont
        }

        if Task.isCancelled { throw CancellationError() }
        return result
    }

    // MARK: - Recognition helpers

    nonisolated private func handleRecognitionSuccess(
        result: SFSpeechRecognitionResult,
        expectation: RecognitionContext.Expectation,
        inactivity: TimeInterval
    ) {
        let rawText = result.bestTranscription.formattedString
        let trimmed = rawText.trimmingCharacters(in: .whitespacesAndNewlines)
        // Extract segment timings before crossing actor boundary.
        let segmentTimings = result.bestTranscription.segments.map { ($0.timestamp, $0.duration) }

        Task {
            await MainActor.run {
                var text = rawText
                if case .number = expectation {
                    text = Self.normalizeNumeric(from: text)
                }

                if !trimmed.isEmpty {
                    self.transcript = text
                    self.startInactivityTimer(seconds: inactivity)
                }

                self.updateSpeechSegmentTimings(segmentTimings)

                if result.isFinal {
                    self.log(.info, "listen(stt) complete via recognizer isFinal")
                    self.completeCurrentListen()
                }
            }
        }
    }

    private func updateSpeechSegments(_ segments: [SFTranscriptionSegment]) {
        let timings = segments.map { ($0.timestamp, $0.duration) }
        updateSpeechSegmentTimings(timings)
    }

    private func updateSpeechSegmentTimings(_ timings: [(TimeInterval, TimeInterval)]) {
        guard !timings.isEmpty else { return }
        var first = firstSpeechStart
        var last = lastSpeechEnd
        for (timestamp, duration) in timings {
            if first == nil { first = timestamp }
            last = max(last ?? 0, timestamp + duration)
        }
        firstSpeechStart = first
        lastSpeechEnd = last
    }

    // MARK: - Private helpers (STT listen setup)

    /// Build and configure the speech recognition request and recognizer
    /// based on the current recognitionContext.
    private func prepareRecognitionRequest() throws -> (SFSpeechAudioBufferRecognitionRequest, SFSpeechRecognizer) {
        let request = SFSpeechAudioBufferRecognitionRequest()
        request.shouldReportPartialResults = true

        switch recognitionContext.expectation {
        case .freeform:
            request.taskHint = .dictation
        case .name(let allowed):
            request.taskHint = .dictation
            request.contextualStrings = allowed
        case .number:
            request.taskHint = .search
            request.contextualStrings = RecognitionContext.numericContextualStrings
        }

        if #available(iOS 13.0, macOS 10.15, *),
           let recognizer = speechRecognizer,
           recognizer.supportsOnDeviceRecognition {
            request.requiresOnDeviceRecognition = true
        }

        guard let recognizer = speechRecognizer, recognizer.isAvailable else {
            throw VoiceIOError.recognizerUnavailable
        }

        recognitionRequest = request
        return (request, recognizer)
    }

    /// Create an optional raw recording file for this listen. We never fail the overall
    /// listen if file creation fails; STT still runs normally.
    private func makeRecordingFileIfNeeded(for format: AVAudioFormat,
                                           record: Bool) -> AVAudioFile? {
        guard record else {
            rawRecordingURL = nil
            return nil
        }
        do {
            let base = "vk-listen-\(UUID().uuidString).caf"
            let url = FileManager.default.temporaryDirectory.appendingPathComponent(base)
            rawRecordingURL = url
            return try AVAudioFile(forWriting: url, settings: format.settings)
        } catch {
            // Fall back to STT-only; recordingURL will remain nil.
            rawRecordingURL = nil
            return nil
        }
    }

}
