//
//  RealVoiceIO+Numeric.swift
//  VoiceKit
//
//  Numeric normalization helpers used by the STT pipeline.
//  Extracted from RealVoiceIO+STT.swift to keep that file focused and
//  under lint file-length limits.
//
//  Generated by GPT-5 (OpenAI) - collaborator: rdoggett
//  date: 12-03-2025
//

import Foundation

@MainActor
extension RealVoiceIO {

    // MARK: - Numeric normalization helpers

    /// Build decimal digits after the "point" token; returns nil if any token is unrecognized.
    internal static func decimalDigits(
        from tokens: ArraySlice<String>,
        ones: [String: Int]
    ) -> String? {
        var dec = ""
        for word in tokens {
            if let digit = ones[word] {
                dec.append(String(digit))
            } else if let number = Int(word) {
                dec.append(String(number))
            } else {
                return nil
            }
        }
        return dec.isEmpty ? "0" : dec
    }

    /// Converts simple number words into digits (e.g., "seven" -> "7",
    /// "Nineteen" -> "19", "forty-two point five" -> "42.5").
    /// Falls back to the trimmed original if tokens are unrecognized.
    public static func normalizeNumeric(from string: String) -> String {
        let trimmed = string
            .replacingOccurrences(of: "\\s+", with: " ", options: .regularExpression)
            .trimmingCharacters(in: .whitespacesAndNewlines)

        if trimmed.isEmpty { return trimmed }

        let lower = trimmed.lowercased()
        let tokens = lower
            .replacingOccurrences(of: "-", with: " ")
            .split(separator: " ")
            .map(String.init)

        guard let (intValue, decimalPart) = parseNumericTokens(tokens) else {
            return trimmed
        }

        if let intValue {
            if let dec = decimalPart {
                return "\(intValue).\(dec)"
            } else {
                return "\(intValue)"
            }
        }

        return trimmed
    }

    /// Parse token array into integer and optional decimal parts.
    /// Returns nil if any token is unrecognized or invalid.
    /// Handles: ones, teens, tens, hundreds, thousands, millions and decimal parts.
    /// Example: "one thousand two hundred thirty four" → 1234
    ///          "forty two" → 42
    ///          "five point three" → 5.3
    private static func parseNumericTokens(_ tokens: [String]) -> (intValue: Int?, decimalPart: String?)? {
        let ones: [String: Int] = [
            "zero": 0, "one": 1, "two": 2, "three": 3, "four": 4,
            "five": 5, "six": 6, "seven": 7, "eight": 8, "nine": 9
        ]
        let teens: [String: Int] = [
            "ten": 10, "eleven": 11, "twelve": 12, "thirteen": 13, "fourteen": 14,
            "fifteen": 15, "sixteen": 16, "seventeen": 17, "eighteen": 18, "nineteen": 19
        ]
        let tens: [String: Int] = [
            "twenty": 20, "thirty": 30, "forty": 40, "fifty": 50,
            "sixty": 60, "seventy": 70, "eighty": 80, "ninety": 90
        ]
        let scales: [String: Int] = [
            "hundred": 100, "thousand": 1000, "million": 1000000
        ]

        var intValue: Int?
        var decimalPart: String?
        var current = 0 // Accumulator for the current scale (before multiplying by hundred/thousand/million)
        var i = 0

        while i < tokens.count {
            let token = tokens[i]

            if token == "point" {
                if let dec = Self.decimalDigits(from: tokens[(i + 1)...], ones: ones) {
                    decimalPart = dec
                } else {
                    return nil
                }
                break
            }

            // Check for scale multipliers (hundred, thousand, million)
            if let scale = scales[token] {
                if scale < 1000 {
                    // "hundred" multiplies the current accumulator
                    current = (current == 0 ? 1 : current) * scale
                } else {
                    // "thousand" and "million" multiply and add to total
                    let toAdd = (current == 0 ? 1 : current) * scale
                    intValue = (intValue ?? 0) + toAdd
                    current = 0
                }
                i += 1
                continue
            }

            if let teenValue = teens[token] {
                current += teenValue
                i += 1
                continue
            }

            if let tensValue = tens[token] {
                var value = tensValue
                if i + 1 < tokens.count, let onesDigit = ones[tokens[i + 1]] {
                    value += onesDigit
                    i += 1
                }
                current += value
                i += 1
                continue
            }

            if let digitValue = ones[token] {
                current += digitValue
                i += 1
                continue
            }

            if let num = Int(token) {
                current += num
                i += 1
                continue
            }

            if Double(token) != nil {
                return nil
            }

            return nil
        }

        // Add any remaining accumulated value to the total
        if current > 0 {
            intValue = (intValue ?? 0) + current
        }

        return (intValue, decimalPart)
    }

    /// Backward-compat unlabeled version.
    public static func normalizeNumeric(_ string: String) -> String {
        normalizeNumeric(from: string)
    }
}
