//
//  STTActivityTracker.swift
//  VoiceKit
//
//  Tracks when we last observed "loud" audio in the mic stream.
//  Used to decide when the user has gone quiet, independent of STT partials.
//
//  Generated by Claude Haiku 4.5 (Anthropic) — collaborator: rdoggett
//  date: 03-09-2026
//

import Foundation

// Tracks when we last observed "loud" audio in the mic stream.
// Used to decide when the user has gone quiet, independent of STT partials.
internal actor STTActivityTracker {
    private var lastLoudTime: TimeInterval?
    // Simple adaptive estimate of background noise in dB.
    // Starts at nil; seeded from early observations.
    private var baselineDB: Float?

    /// Observe a new buffer loudness in dB at the given uptime.
    /// - Updates the baseline (noise floor) over time.
    /// - Updates lastLoudTime only when the buffer is sufficiently louder
    ///   than the baseline (speech vs. background).
    func observe(db: Float, at time: TimeInterval) {
        // Seed baseline from first sample.
        if baselineDB == nil {
            baselineDB = db
        }

        guard let currentBaseline = baselineDB else { return }

        // Exponential moving average toward the observed db.
        // Use a small alpha so the baseline moves slowly and reflects
        // ambient conditions rather than every transient spike.
        let alpha: Float = 0.05
        let newBaseline = currentBaseline + alpha * (db - currentBaseline)
        baselineDB = newBaseline

        // Margin above baseline to consider this "speech" instead of noise.
        // This is deliberately modest; we still have an inactivity timeout
        // and trimming on the raw recording to refine bounds.
        let margin: Float = 12.0
        if db >= newBaseline + margin {
            markLoud(at: time)
        }
    }

    func markLoud(at time: TimeInterval) {
        // Only move forward in time.
        if let current = lastLoudTime {
            if time > current { lastLoudTime = time }
        } else {
            lastLoudTime = time
        }
    }

    func lastLoud() -> TimeInterval? { lastLoudTime }

    func reset(now: TimeInterval? = nil) {
        baselineDB = nil
        lastLoudTime = now
    }
}
