//
//  VoicePublic.swift
//  VoiceKit
//
//  Generated by GPT-5.1 (OpenAI) - collaborator: rdoggett
//  date: 11-19-2025
//

import Foundation
import CoreGraphics

// Tuning is the canonical control model (rateVariation, pitchVariation, volume).

// MARK: - Public results and errors

public struct VoiceResult: Sendable {
    public let transcript: String
    public let recordingURL: URL?

    public init(transcript: String, recordingURL: URL?) {
        self.transcript = transcript
        self.recordingURL = recordingURL
    }
}

// MARK: - VoiceIO API (main-actor)

/// App-facing voice box surface.
/// Owns speaking, listening, short clips, lifecycle, and UI callbacks.
@MainActor
public protocol VoiceIO: AnyObject {
    var onListeningChanged: ((Bool) -> Void)? { get set }
    var onTranscriptChanged: ((String) -> Void)? { get set }
    var onLevelChanged: ((CGFloat) -> Void)? { get set }
    var onTTSSpeakingChanged: ((Bool) -> Void)? { get set }
    var onTTSPulse: ((CGFloat) -> Void)? { get set }
    var onStatusMessageChanged: ((String?) -> Void)? { get set }

    func ensurePermissions() async throws
    func configureSessionIfNeeded() async throws

    func speak(_ text: String) async
    func listen(timeout: TimeInterval, inactivity: TimeInterval, record: Bool) async throws -> VoiceResult

    func prepareClip(url: URL, gainDB: Float) async throws
    func startPreparedClip() async throws
    func playClip(url: URL, gainDB: Float) async throws

    func stopAll()
    func hardReset()
}

@MainActor
public extension VoiceIO {
    func prepareClip(url: URL) async throws { try await prepareClip(url: url, gainDB: 0) }
    func playClip(url: URL) async throws { try await playClip(url: url, gainDB: 0) }
    func queueSFX(url: URL, gainDB: Float = 0) async throws { try await prepareClip(url: url, gainDB: gainDB) }

    func listen(timeout: TimeInterval,
                inactivity: TimeInterval,
                record: Bool,
                context: RecognitionContext = .init()) async throws -> VoiceResult {
        if let real = self as? RealVoiceIO {
            real.setRecognitionContext(context)
        }
        return try await listen(timeout: timeout, inactivity: inactivity, record: record)
    }
}

/// Convenience seam for types that are both a VoiceIO and TTSConfigurable.
/// RealVoiceIO conforms; helpers that need both "box" and "tuning/preview"
/// (e.g., VoiceChorus, VoiceChooserViewModel) can depend on this instead of
/// spelling the intersection every time.
public typealias VoiceEngine = any VoiceIO & TTSConfigurable

// MARK: - TTS models and configuration

public struct TTSVoiceInfo: Identifiable, Hashable, Codable, Sendable {
    public let id: String
    public let name: String
    public let language: String

    public init(id: String, name: String, language: String) {
        self.id = id
        self.name = name
        self.language = language
    }
}

/// Per-voice speaking profile: rate (pace), pitch (tone), and volume (amplitude).
///
/// **rate**: Normalized speaking pace in [0, 1]. Zero is slowest; 1.0 is fastest.
/// - Struct default (when constructed directly): 0.5 (perceptually linear midpoint)
/// - Application default (via VoiceProfilesStore): 0.55 (slightly conversational for most voices)
/// System range: `AVSpeechUtterance.rate` maps to [0.1, 10.0] internally, but
/// perception is approximately linear in the range [0.3, 1.0].
/// **Interaction with Tuning**: `Tuning.rateVariation` is applied as a random jitter
/// around this profile rate at synthesis time, creating more natural variation.
///
/// **pitch**: Relative pitch multiplier in [0.5, 2.0]. One is neutral voice tone;
/// < 1 produces lower pitch; > 1 produces higher pitch.
/// Default: 1.0. Maps to `AVSpeechUtterance.pitchMultiplier`.
///
/// **volume**: Relative amplitude in [0, 1]. Zero is silent; 1.0 is full volume.
/// - Struct default: 1.0
/// - Application default (via VoiceProfilesStore): 0.9
/// Applied at synthesis time. Maps to `AVSpeechUtterance.volume`.
///
/// **Mutability**: The voice id (`id`) is immutable, making profiles safe to share
/// and cache. Rate, pitch, and volume are mutable for runtime tuning via UI or
/// automation. When constructing profiles directly (not via store), consider using
/// the store defaults (0.55 rate, 0.9 volume) for UI consistency.
public struct TTSVoiceProfile: Sendable, Equatable, Codable {
    public let id: String
    public var rate: Double
    public var pitch: Float
    public var volume: Float

    public init(id: String, rate: Double = 0.5, pitch: Float = 1.0, volume: Float = 1.0) {
        self.id = id
        self.rate = rate
        self.pitch = pitch
        self.volume = volume
    }
}

public struct Tuning: Sendable, Equatable, Codable {
    public var rateVariation: Float
    public var pitchVariation: Float
    public var volume: Float

    public init(rateVariation: Float = 0,
                pitchVariation: Float = 0,
                volume: Float = 1.0) {
        self.rateVariation = rateVariation
        self.pitchVariation = pitchVariation
        self.volume = volume
    }
}

/// TTS tuning + preview surface.
/// Lets UI and helpers configure voice profiles and tuning, then speak
/// short utterances for a specific voice id.
@MainActor
public protocol TTSConfigurable: AnyObject {
    func setVoiceProfile(_ profile: TTSVoiceProfile)
    func getVoiceProfile(id: String) -> TTSVoiceProfile?
    func setDefaultVoiceProfile(_ profile: TTSVoiceProfile)
    func getDefaultVoiceProfile() -> TTSVoiceProfile?
    func setTuning(_ tuning: Tuning)
    func getTuning() -> Tuning

    /// Speak text using an optional voice profile id (nil uses default).
    func speak(_ text: String, using voiceID: String?) async
}

// MARK: - Recognition context

public struct RecognitionContext: Sendable {
    public enum Expectation: Sendable {
        case freeform
        case name(allowed: [String])
        case number
    }

    public var expectation: Expectation

    public init(expectation: Expectation = .freeform) { self.expectation = expectation }

    /// Convenience helper: returns true if expectation is `.number`.
    public var expectNumber: Bool {
        if case .number = expectation { return true }
        return false
    }
}

public extension RecognitionContext {
    static var numericContextualStrings: [String] {
        let digits = (0...20).map { String($0) } + ["30", "40", "50", "60", "70", "80", "90", "100", "1000"]
        let words = [
            "zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine",
            "ten", "eleven", "twelve", "thirteen", "fourteen", "fifteen",
            "sixteen", "seventeen", "eighteen", "nineteen", "twenty",
            "thirty", "forty", "fifty", "sixty", "seventy", "eighty", "ninety",
            "hundred", "thousand", "million", "point"
        ]
        return digits + words
    }
}

// MARK: - Operation gate

/// A simple async gate for serializing access to a critical section.
///
/// **Purpose**: Prevent concurrent execution of mutually exclusive operations.
/// For example, ensuring that TTS synthesis and STT listening don't overlap,
/// or that voice I/O operations complete before a hard reset.
///
/// **Usage**:
/// ```swift
/// let gate = VoiceOpGate()
/// await gate.acquire()
/// defer { Task { await gate.release() } }
/// // Perform protected operation here
/// ```
///
/// **Limitations**: This is a simple cooperative lock without timeouts or fairness
/// guarantees. If `acquire()` is called and the gate is already held, the caller
/// will poll with a 200μs sleep. For production code requiring timeout or
/// fair queuing, consider using a more sophisticated synchronization primitive.
public actor VoiceOpGate {
    private var busy = false

    public init() {}

    /// Acquire exclusive access, blocking until the gate is free.
    /// No timeout; waits indefinitely if the gate is held by another task.
    public func acquire() async {
        while busy {
            try? await Task.sleep(nanoseconds: 200_000)
        }
        busy = true
    }

    /// Release the gate, allowing other waiters to proceed.
    public func release() async { busy = false }

    /// Force-clear the gate without checking state.
    /// Use only for cleanup/reset after an error.
    public func forceClear() async { busy = false }
}
