//
//  VoiceIOError.swift
//  VoiceKit
//
//  Generated by GPT-5 (OpenAI)
//  collaborator: rdoggett
//  date: 09-17-2025
//

import Foundation

/// Canonical errors surfaced by RealVoiceIO public API.
public enum VoiceIOError: Error, Equatable, Sendable {
    /// The device microphone is not available or input route is missing.
    case micUnavailable
    /// The system SFSpeechRecognizer is not available for the requested locale/device.
    case recognizerUnavailable
    /// The audio input format was invalid or could not be prepared.
    case audioFormatInvalid
    /// The operation exceeded its configured timeout.
    case timedOut
    /// The operation was cancelled by the caller or task.
    case cancelled
    /// An underlying error occurred. Inspect the message for hints.
    case underlying(String)
}
