//
//  VoiceIOConfig.swift
//  VoiceKit
//
//  Generated by GPT-5 (OpenAI)
//  collaborator: rdoggett
//  date: 09-17-2025
//

import Foundation

/// Configuration for RealVoiceIO behavior.
/// All values have sensible defaults suitable for most applications.
///
/// Invalid values (negative, NaN, or infinity) are automatically clamped to safe ranges
/// to prevent undefined behavior at runtime. This allows safe construction from user input
/// or untrusted sources without requiring pre-validation.
public struct VoiceIOConfig: Sendable, Equatable {
    /// Padding to add before the detected start of speech when trimming recordings (seconds).
    /// Automatically clamped to [0, 1.0]. Typical values: 0.05 to 0.1. Allows capturing slight lead-in.
    public var trimPrePad: Double

    /// Padding to add after the detected end of speech when trimming recordings (seconds).
    /// Automatically clamped to [0, 2.0]. Typical values: 0.1 to 0.3. Allows capturing slight tail-out and breath.
    public var trimPostPad: Double

    /// Maximum time to wait for a prepared clip to start playback before timing out (seconds).
    /// Automatically clamped to (0, 60.0]. Intended for boosted clip scheduling, but currently unused in VoiceKit.
    /// Retained for potential future use or app-level integration.
    /// Default (2.0) would accommodate system audio setup delays if implemented.
    public var clipWaitTimeoutSeconds: Double

    /// Duration to suppress STT listening after TTS finishes speaking (seconds).
    /// Automatically clamped to [0, 5.0]. A value of 0 disables suppression. Intended to prevent
    /// the recognizer from hearing back the speaker's own voice, but currently unused in VoiceKit
    /// (STT and TTS are not auto-coordinated). Retained for potential future use or app-level integration.
    /// Typical value if implemented: 0.2 to 0.5 depending on speaker volume and environment.
    public var ttsSuppressAfterFinish: Double

    /// Initializes a configuration with custom values.
    ///
    /// - Parameters:
    ///   - trimPrePad: Pre-speech padding in seconds (default: 0.05; clamped to [0, 1.0])
    ///   - trimPostPad: Post-speech padding in seconds (default: 0.20; clamped to [0, 2.0])
    ///   - clipWaitTimeoutSeconds: Clip startup timeout in seconds (default: 2.0; clamped to (0, 60.0])
    ///   - ttsSuppressAfterFinish: STT suppression after TTS in seconds (default: 0.25; clamped to [0, 5.0])
    ///
    /// All values are validated and clamped to safe ranges. NaN and infinite values are treated as 0
    /// (for padding/suppress fields) or 0.1 (for timeout fields), then clamped to the valid range.
    public init(trimPrePad: Double = 0.05,
                trimPostPad: Double = 0.20,
                clipWaitTimeoutSeconds: Double = 2.0,
                ttsSuppressAfterFinish: Double = 0.25) {
        // Validate and clamp padding values (must be >= 0)
        let validTrimPrePad = trimPrePad.isFinite && trimPrePad >= 0 ? trimPrePad : 0
        let validTrimPostPad = trimPostPad.isFinite && trimPostPad >= 0 ? trimPostPad : 0

        // Validate and clamp timeout values (must be > 0)
        let validClipTimeout = clipWaitTimeoutSeconds.isFinite && clipWaitTimeoutSeconds > 0
            ? clipWaitTimeoutSeconds : 0.1
        let validTtsSuppress = ttsSuppressAfterFinish.isFinite && ttsSuppressAfterFinish >= 0
            ? ttsSuppressAfterFinish : 0

        self.trimPrePad = min(validTrimPrePad, 1.0)
        self.trimPostPad = min(validTrimPostPad, 2.0)
        self.clipWaitTimeoutSeconds = min(max(validClipTimeout, 0.01), 60.0)
        self.ttsSuppressAfterFinish = min(validTtsSuppress, 5.0)
    }
}
