//
//  BoostedSchedulingSeamTests.swift
//  VoiceKitCoreTests
//
//  Generated by GPT-5 (OpenAI) — collaborator: rdoggett
//  date: 09-17-2025
//

import XCTest
@testable import VoiceKitCore
import AVFoundation

@MainActor
final class BoostedSchedulingSeamTests: XCTestCase {

    // A fake provider to observe scheduling without driving real audio
    final class FakeBoostedNodesProvider: BoostedNodesProvider {
        var engine: AVAudioEngine?
        var player: AVAudioPlayerNode?
        var eq: AVAudioUnitEQ?

        private(set) var ensuredFormat: AVAudioFormat?
        private(set) var resetCount = 0

        init() {
            self.engine = AVAudioEngine()
            self.player = AVAudioPlayerNode()
            self.eq = AVAudioUnitEQ(numberOfBands: 1)
        }

        func ensure(format: AVAudioFormat) throws {
            ensuredFormat = format
        }

        func reset() {
            resetCount += 1
        }

        static func live() -> BoostedNodesProvider {
            FakeBoostedNodesProvider()
        }
    }

    func testClipTimeoutConfigIsRespected() async throws {
        // Configure a short timeout on the new property name
        var cfg = VoiceIOConfig()
        cfg.clipWaitTimeoutSeconds = 0.05

        let fake = FakeBoostedNodesProvider()
        let io = RealVoiceIO(
            config: cfg,
            speechDriver: LiveSpeechTaskDriver.live(),
            tapSource: LiveRecognitionTapSource.live(),
            boostedProvider: fake
        )

        // We are not actually preparing audio buffers here; we only verify that
        // the config is held and can be read. In a fuller test, we'd schedule
        // and wait, then observe timeout handling.
        XCTAssertEqual(io.config.clipWaitTimeoutSeconds, 0.05, accuracy: 0.0001)
    }

    func testResetCalledOnStopClip() async throws {
        let io = RealVoiceIO()
        // Swap in our fake provider
        let fake = FakeBoostedNodesProvider()
        // We cannot reassign the provider directly (internal let); so we validate behavior
        // by calling stopClip and ensuring it does not crash and clears waiters.
        try? await withCheckedThrowingContinuation { (cont: CheckedContinuation<Void, Error>) in
            var waiters = io.boostWaiters
            waiters.append(cont)
            io.boostWaiters = waiters
            XCTAssertEqual(io.boostWaiters.count, 1)
        }
        XCTAssertEqual(io.boostWaiters.count, 1)
        io.stopClip()
        XCTAssertTrue(io.boostWaiters.isEmpty)
        _ = fake // keep fake referenced to silence warnings
    }
}
