//
//  CoreSanityTests.swift
//  VoiceKit
//
//  Created by robert on 9/12/25.
//


//
//  CoreSanityTests.swift
//  VoiceKitCoreTests
//
//  Generated by GPT-5 (OpenAI) — collaborator: rdoggett
//  date: 09-12-2025
//

import XCTest
import VoiceKitCore

@MainActor
final class CoreSanityTests: XCTestCase {

    func testCanCreateAndHardReset() async throws {
        // This should not trigger any permission UI by itself.
        // It validates actor-safety and basic initialization on main.
        let io = RealVoiceIO()
        io.hardReset()
        XCTAssertTrue(true)
    }

    func testPublicTypesAreReachable() {
        // Construct a few public types to confirm visibility and linkage
        let _ = RealVoiceIO.Config()
        let _ = RecognitionContext(expectation: .freeform)
        let _ = TTSMasterControl()
        let _ = TTSVoiceProfile(id: "v.test", displayName: "Test", rate: 0.5, pitch: 1.0, volume: 1.0)
        XCTAssertTrue(true)
    }
}
