//
//  NameMatchTokenDistanceTests.swift
//  VoiceKitCoreTests
//
//  Generated by GPT-5 (OpenAI) — collaborator: rdoggett
//  date: 09-14-2025
//

import XCTest
import VoiceKitCore

final class NameMatchTokenDistanceTests: XCTestCase {

    func testIdenticalIsZero() {
        let key = NameMatch.normalizeKey("Jean-Luc Picard")
        XCTAssertEqual(NameMatch.stringDistanceScore(a: key, b: key), 0)
    }

    func testMissingTokenPenalizedButNotMax() {
        let a = NameMatch.normalizeKey("john paul jones")
        let b = NameMatch.normalizeKey("john jones")
        let score = NameMatch.stringDistanceScore(a: a, b: b)
        XCTAssertGreaterThan(score, 0.05)
        XCTAssertLessThan(score, 0.8)
    }

    func testCrossTokenMatchingPicksBestPairs() {
        let a = NameMatch.normalizeKey("katherine anne")
        let b = NameMatch.normalizeKey("catherine ann")
        let score = NameMatch.stringDistanceScore(a: a, b: b)
        XCTAssertLessThan(score, 0.35)
    }
}
