//
//  RealVoiceIOBoostedTests.swift
//  VoiceKitCoreTests
//
//  Updated to match idempotent boosted semantics:
//  - Adding a waiter via boostWaiters immediately resumes it and does not retain it.
//  - stopClip() is idempotent and clears any remaining waiters without double-resume.
//
//  Generated by GPT-5 (OpenAI) — collaborator: rdoggett
//  date: 09-20-2025
//

import XCTest
@testable import VoiceKitCore
import AVFoundation

@MainActor
final class RealVoiceIOBoostedTests: XCTestCase {

    func testNewlyAddedWaitersAreImmediatelyResumedAndNotRetained() async throws {
        let io = RealVoiceIO()

        // Ensure clean state
        XCTAssertTrue(io.boostWaiters.isEmpty)

        // Add two continuations; each should be immediately resumed and not kept
        for _ in 0..<2 {
            try await withCheckedThrowingContinuation { (cont: CheckedContinuation<Void, Error>) in
                var waiters = io.boostWaiters
                waiters.append(cont)
                io.boostWaiters = waiters
            }
        }

        // Storage should not grow because we don't retain already-resumed continuations
        XCTAssertTrue(io.boostWaiters.isEmpty)
    }

    func testStopClipIsIdempotentAndClearsWaiters() async throws {
        let io = RealVoiceIO()

        // Add a waiter (immediately resumed and not stored)
        try await withCheckedThrowingContinuation { (cont: CheckedContinuation<Void, Error>) in
            var waiters = io.boostWaiters
            waiters.append(cont)
            io.boostWaiters = waiters
        }
        XCTAssertTrue(io.boostWaiters.isEmpty)

        // Call stopClip twice; should not crash and should remain empty
        io.stopClip()
        XCTAssertTrue(io.boostWaiters.isEmpty)

        io.stopClip()
        XCTAssertTrue(io.boostWaiters.isEmpty)
    }

    func testPrepareResetsCompletionFlagAndClearsStaleWaiters() async throws {
        let io = RealVoiceIO()

        // Simulate completion by calling stop, then prepare a new clip
        io.stopClip()
        // Prepare a new clip should reset completion flag and clear waiters
        try await io.prepareBoosted(url: FileManager.default.temporaryDirectory.appendingPathComponent("dummy.caf"), gainDB: 0)

        // Add another waiter; it should still immediately resume and not be retained
        try await withCheckedThrowingContinuation { (cont: CheckedContinuation<Void, Error>) in
            var waiters = io.boostWaiters
            waiters.append(cont)
            io.boostWaiters = waiters
        }
        XCTAssertTrue(io.boostWaiters.isEmpty)
    }
}
