//
//  VoiceOpGateForceClearTests.swift
//  VoiceKit
//
//  Created by robert on 9/14/25.
//


//
//  VoiceOpGateForceClearTests.swift
//  VoiceKitCoreTests
//
//  Generated by GPT-5 (OpenAI) — collaborator: rdoggett
//  date: 09-14-2025
//

import XCTest
import VoiceKitCore

final class VoiceOpGateForceClearTests: XCTestCase {

    func testForceClearAllowsImmediateAcquire() async {
        let gate = VoiceOpGate()
        await gate.acquire()
        await gate.forceClear() // forget lock without waiting
        // Should not block
        await gate.acquire()
        await gate.release()
        XCTAssertTrue(true)
    }
}