//
//  VoiceKitInfoTests.swift
//  VoiceKitCoreTests
//
//  Generated by GPT-5 (OpenAI) — collaborator: rdoggett
//  date: 09-17-2025
//

import XCTest
import VoiceKitCore

final class VoiceKitInfoTests: XCTestCase {

    func testVersionNonEmpty() {
        XCTAssertFalse(VoiceKitInfo.version.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty)
    }

    func testBuildTimestampIsISO8601() {
        let ts = VoiceKitInfo.buildTimestampISO8601
        let fmt = ISO8601DateFormatter()
        XCTAssertNotNil(fmt.date(from: ts), "Timestamp should be ISO8601 parseable")
    }
}
