//
//  VoiceOpGateTests.swift
//  VoiceKit
//
//  Generated by GPT-5 (OpenAI) — collaborator: rdoggett
//  date: 09-13-2025
//

import XCTest
import VoiceKitCore

final class VoiceOpGateTests: XCTestCase {

    func testGateSerializesAccess() async throws {
        let gate = VoiceOpGate()
        let start = Date()

        async let first: Void = {
            await gate.acquire()
            try? await Task.sleep(nanoseconds: 120_000_000)
            await gate.release()
        }()

        // Stagger second acquire slightly later; it must wait for the first to release.
        try? await Task.sleep(nanoseconds: 10_000_000)
        async let second: Void = {
            await gate.acquire()
            // Record elapsed once we enter; it should be >= ~120ms.
            let elapsed = Date().timeIntervalSince(start)
            XCTAssertGreaterThanOrEqual(elapsed, 0.11, "Second acquire should wait for first to release")
            await gate.release()
        }()

        _ = await (first, second)
    }
}
