//
//  VoiceProfilesStoreToggleTests.swift
//  VoiceKit
//
//  Created by robert on 9/14/25.
//


//
//  VoiceProfilesStoreToggleTests.swift
//  VoiceKitUITests
//
//  Generated by GPT-5 (OpenAI) — collaborator: rdoggett
//  date: 09-14-2025
//

import XCTest
import VoiceKitCore
import VoiceKitUI

@MainActor
final class VoiceProfilesStoreToggleTests: XCTestCase {

    func testActiveAndHiddenPersist() {
        let filename = "store-\(UUID().uuidString).json"
        let store1 = VoiceProfilesStore(filename: filename)
        let info1 = TTSVoiceInfo(id: "v.a", name: "Alpha", language: "en-US")
        let info2 = TTSVoiceInfo(id: "v.b", name: "Beta", language: "en-US")

        // Accessing profile should create defaults
        let p1 = store1.profile(for: info1)
        XCTAssertEqual(p1.displayName, "Alpha")

        // Toggle active and hidden
        store1.toggleActive(info1.id) // add
        store1.toggleActive(info2.id) // add
        store1.toggleActive(info2.id) // remove
        store1.setHidden(info1.id, true)

        store1.defaultVoiceID = info1.id
        store1.save()

        // Reload
        let store2 = VoiceProfilesStore(filename: filename)
        XCTAssertTrue(store2.isActive(info1.id))
        XCTAssertFalse(store2.isActive(info2.id))
        XCTAssertTrue(store2.isHidden(info1.id))
        XCTAssertEqual(store2.defaultVoiceID, info1.id)

        // Unhide and save again
        store2.setHidden(info1.id, false)
        store2.save()
        let store3 = VoiceProfilesStore(filename: filename)
        XCTAssertFalse(store3.isHidden(info1.id))
    }
}
