//
//  VoiceProfilesStoreToggleTests.swift
//  VoiceKit
//
//  Generated by GPT-5 (OpenAI) - collaborator: rdoggett
//  date: 09-14-2025
//

import XCTest
@testable import VoiceKitUI
@testable import VoiceKit

@MainActor
internal final class VoiceProfilesStoreToggleTests: XCTestCase {

    func testHiddenTogglePersists() throws {
        let store = VoiceProfilesStore(filename: "test_hidden.json")
        defer { try? FileManager.default.removeItem(at: storeTestURL("test_hidden.json")) }

        let id = "com.apple.speech.synthesis.voice.Alex"
        store.setProfile(TTSVoiceProfile(id: id, rate: 0.5, pitch: 1.0, volume: 1.0))

        XCTAssertFalse(store.isHidden(id))
        store.setHidden(id, true)
        XCTAssertTrue(store.isHidden(id))

        store.save()
        let loaded = VoiceProfilesStore(filename: "test_hidden.json")
        XCTAssertTrue(loaded.isHidden(id))

        loaded.setHidden(id, false)
        XCTAssertFalse(loaded.isHidden(id))
    }

    private func storeTestURL(_ filename: String) -> URL {
        let appSupport = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask).first
            ?? FileManager.default.temporaryDirectory
        let dir = appSupport.appendingPathComponent("VoiceIO", isDirectory: true)
        return dir.appendingPathComponent(filename)
    }
}
