//
//  ChorusLabActionRowView+Init.swift
//  VoiceKitUI
//
//  Public convenience initializer for ChorusLabActionRowView.
//
//  Generated by GPT-5 (OpenAI) — collaborator: rdoggett
//  date: 11-13-2025
//

import SwiftUI

public extension ChorusLabActionRowView {
    init(playing isPlaying: Binding<Bool>,
         calibrating isCalibrating: Binding<Bool>,
         hasSelection: Bool,
         onPlay: @escaping () -> Void,
         onStop: @escaping () -> Void,
         onSync: @escaping () -> Void) {
        self.init(
            isPlaying: isPlaying,
            isCalibrating: isCalibrating,
            hasSelection: hasSelection,
            onPlay: onPlay, onStop: onStop, onSync: onSync
        )
    }
}
 
