//
//  ChorusLabSelectedVoiceRow.swift
//  VoiceKit
//
//  Row displaying selected voice name, compact settings, and last duration.
//  Generated by GPT-5 (OpenAI) - collaborator: rdoggett
//  date: 10-31-2025
//

import SwiftUI
import VoiceKitUI

@MainActor
public struct ChorusLabSelectedVoiceRow: View {
    let name: String
    let rate: Double
    let pitch: Float
    let volume: Float
    let duration: TimeInterval?
    let isCalibrating: Bool
    var timingCellWidth: CGFloat = 42

    public var body: some View {
        HStack(alignment: .firstTextBaseline, spacing: 8) {
            // Name (left)
            Text(name)
                .font(.subheadline)
                .lineLimit(1)
                .minimumScaleFactor(0.9)
                .allowsTightening(true)
                .truncationMode(.tail)
                .layoutPriority(1)
                .frame(maxWidth: .infinity, alignment: .leading)
                .accessibilityLabel("Voice name")
                .accessibilityValue(Text(name))

            Spacer(minLength: 0)

            // Details (middle)
            DetailsCell(rate: rate, pitch: pitch, volume: volume)
                .accessibilityLabel("Voice settings")
                .accessibilityValue(
                    Text("Speed \(rate.formatted()), Pitch \(pitch.formatted()), Volume \(volume.formatted())"))

            // Timing (right)
            DurationCell(duration: duration, isHighlighted: isCalibrating, width: timingCellWidth)
                .accessibilityLabel("Last duration")
                .accessibilityValue(Text(duration.map { $0.formatted(suffix: "s") } ?? "Not measured"))

            Image(systemName: "chevron.right")
                .font(.caption2)
                .foregroundStyle(.tertiary)
                .frame(width: 6, alignment: .trailing)
                .accessibilityHidden(true)
        }
        .accessibilityAddTraits(.isButton)
    }
}

// MARK: - Small helper cells
@MainActor
private struct DetailsCell: View {
    let rate: Double
    let pitch: Float
    let volume: Float
    var body: some View {
        Text(["S \(rate.formatted())",
              "P \(pitch.formatted())",
              "Vol \(volume.formatted())"]
            .joined(separator: " · ")
        )
        .font(.caption2)
        .foregroundStyle(.secondary)
        .lineLimit(1)
        .minimumScaleFactor(0.9)
        .allowsTightening(true)
        .frame(minWidth: 150, maxWidth: 220, alignment: .trailing)
    }
}

@MainActor
private struct DurationCell: View {
    let duration: TimeInterval?
    let isHighlighted: Bool
    let width: CGFloat
    var body: some View {
        let text = duration.map { $0.formatted(suffix: "s") } ?? ""
        Text(text)
            .font(.footnote)
            .monospacedDigit()
            .foregroundStyle(duration == nil ? .secondary : .primary)
            .frame(width: width, alignment: .trailing)
            .padding(.vertical, 2)
            .background {
                if isHighlighted {
                    RoundedRectangle(cornerRadius: 4)
                        .fill(Color.green.opacity(0.18))
                }
            }
            .animation(.easeInOut(duration: 0.2), value: isHighlighted)
    }
}

#if DEBUG
@MainActor
internal struct ChorusLabSelectedVoiceRow_Previews: PreviewProvider {
    private struct PreviewWrapper: View {
        @State private var highlight = true
        var body: some View {
            VStack(alignment: .leading, spacing: 12) {
                ChorusLabSelectedVoiceRow(
                    name: "Alex",
                    rate: 0.55,
                    pitch: 1.00,
                    volume: 0.80,
                    duration: 2.48,
                    isCalibrating: highlight
                )
                ChorusLabSelectedVoiceRow(
                    name: "Samantha",
                    rate: 0.70,
                    pitch: 1.15,
                    volume: 0.90,
                    duration: nil,
                    isCalibrating: false
                )
            }
            .padding()
        }
    }

    internal static var previews: some View {
        PreviewWrapper()
            .previewDisplayName("ChorusLabSelectedVoiceRow · iPhone SE (3rd gen)")
            .previewDevice("iPhone SE (3rd generation)")
    }
}
#endif
