//
//  ChorusLabSelectedVoicesSection.swift
//  VoiceKitUI
//
//  Extracted scaffold for the "Selected voices" list section.
//  Next step: move the ForEach row UI and swipe actions here and wire callbacks.
//
//  Generated by GPT-5 (OpenAI) - collaborator: rdoggett
//  date: 10-31-2025
import SwiftUI
import VoiceKit

@MainActor
public struct ChorusLabSelectedVoicesSection: View {
    // Data
    @Binding var profiles: [TTSVoiceProfile]
    @Binding var lastDurationByID: [String: TimeInterval]

    // State
    var isCalibrating: Bool
    var calibratingVoiceID: String?
    var isPlaying: Bool

    // Display helpers
    var resolveName: (_ voiceID: String) -> String
    var timingCellWidth: CGFloat

    // Callbacks
    var onEdit: (_ index: Int) -> Void
    var onSync: (_ voiceID: String) -> Void
    var onDelete: (_ voiceID: String) -> Void

    public init(
        profiles: Binding<[TTSVoiceProfile]>,
        lastDurationByID: Binding<[String: TimeInterval]>,
        isCalibrating: Bool,
        calibratingVoiceID: String?,
        isPlaying: Bool,
        resolveName: @escaping (_ voiceID: String) -> String,
        timingCellWidth: CGFloat,
        onEdit: @escaping (_ index: Int) -> Void,
        onSync: @escaping (_ voiceID: String) -> Void,
        onDelete: @escaping (_ voiceID: String) -> Void
    ) {
        self._profiles = profiles
        self._lastDurationByID = lastDurationByID
        self.isCalibrating = isCalibrating
        self.calibratingVoiceID = calibratingVoiceID
        self.isPlaying = isPlaying
        self.resolveName = resolveName
        self.timingCellWidth = timingCellWidth
        self.onEdit = onEdit
        self.onSync = onSync
        self.onDelete = onDelete
    }

    public var body: some View {
        // Use indices as row IDs so duplicate voice IDs (same system voice
        // with different pitch/volume) render independently.
        ForEach(Array(profiles.indices), id: \.self) { index in
            let profileValue = profiles[index]
            ChorusLabSelectedVoiceRow(
                name: resolveName(profileValue.id),
                rate: profileValue.rate,
                pitch: profileValue.pitch,
                volume: profileValue.volume,
                duration: lastDurationByID[profileValue.id],
                isCalibrating: calibratingVoiceID == profileValue.id,
                timingCellWidth: timingCellWidth
            )
            .contentShape(Rectangle())
            .onTapGesture {
                onEdit(index)
            }
            .swipeActions(edge: .trailing, allowsFullSwipe: true) {
                // Put Sync first so full-swipe defaults to Sync (safer than Delete).
                Button {
                    onSync(profileValue.id)
                } label: {
                    Label("Sync", systemImage: "arrow.clockwise")
                }
                .disabled(isCalibrating || isPlaying)
                .tint(.blue)
                .accessibilityLabel("Synchronize this voice")
                .accessibilityHint("Calibrate this voice to the target time")

                Button(role: .destructive) {
                    onDelete(profileValue.id)
                } label: {
                    Label("Delete", systemImage: "trash")
                }
                .disabled(isCalibrating || isPlaying)
                .accessibilityLabel("Delete voice")
            }
        }
    }
}

#if DEBUG
@MainActor
internal struct ChorusLabSelectedVoicesSection_Previews: PreviewProvider {
    internal static var previews: some View {
        PreviewWrapper()
            .previewLayout(.sizeThatFits)
            .padding()
    }

    private struct PreviewWrapper: View {
        @State private var profiles: [TTSVoiceProfile] = [
            TTSVoiceProfile(id: "voice.alex", rate: 0.55, pitch: 1.00, volume: 1.00),
            TTSVoiceProfile(id: "voice.alex", rate: 0.60, pitch: 1.25, volume: 0.90),
            TTSVoiceProfile(id: "voice.alex", rate: 0.50, pitch: 0.80, volume: 0.85)
        ]
        @State private var lastDurationByID: [String: TimeInterval] = [
            "voice.alex": 2.48
        ]

        var body: some View {
            List {
                ChorusLabSelectedVoicesSection(
                    profiles: $profiles,
                    lastDurationByID: $lastDurationByID,
                    isCalibrating: false,
                    calibratingVoiceID: nil,
                    isPlaying: false,
                    resolveName: { id in id },
                    timingCellWidth: 48,
                    onEdit: { _ in },
                    onSync: { _ in },
                    onDelete: { _ in }
                )
            }
            .listStyle(.automatic)
        }
    }
}
#endif
