//
//  ChorusLabSelectedVoicesSection.swift
//  VoiceKitUI
//
//  Extracted scaffold for the "Selected voices" list section.
//  Renders a row per selected voice with tap/swipe actions for edit, sync, and delete.
//
//  Generated by GPT-5 (OpenAI) - collaborator: rdoggett
//  date: 10-31-2025
import SwiftUI
import VoiceKit

/// List section displaying all selected voices in the chorus with inline controls.
///
/// Each row displays:
/// - Voice name, rate, pitch, volume (from ChorusLabSelectedVoiceRow)
/// - Last measured duration (updated during calibration/playback)
///
/// Interactions:
/// - **Tap**: Open tuner to edit the voice's profile (rate, pitch, volume).
/// - **Swipe right (Sync)**: Calibrate that voice's rate to the target duration.
/// - **Swipe right (Delete)**: Remove the voice from the chorus.
///
/// Rows use indices as identifiers to support duplicate voices (same system voice with different pitch/volume).
@MainActor
public struct ChorusLabSelectedVoicesSection: View {
    /// Array of voice profiles being rendered. Binding allows rows to trigger edits.
    @Binding var profiles: [TTSVoiceProfile]
    /// Map of voice ID → most recent measured duration (updated during calibration).
    @Binding var lastDurationByID: [String: TimeInterval]

    /// Whether rate calibration is currently in progress.
    var isCalibrating: Bool
    /// ID of the voice currently being calibrated (used to highlight its row). Nil if syncing all.
    var calibratingVoiceID: String?
    /// Whether chorus playback is in progress. Controls button enable state.
    var isPlaying: Bool

    /// Closure to resolve a voice ID to its display name (e.g., "Alex", "Victoria").
    var resolveName: (_ voiceID: String) -> String
    /// Width reserved for the timing cell showing measured duration.
    var timingCellWidth: CGFloat

    /// Callback when a row is tapped (opens tuner for editing the voice at given index).
    var onEdit: (_ index: Int) -> Void
    /// Callback when Sync is swiped (calibrate the given voice ID).
    var onSync: (_ voiceID: String) -> Void
    /// Callback when Delete is swiped (remove the given voice ID).
    var onDelete: (_ voiceID: String) -> Void

    public init(
        profiles: Binding<[TTSVoiceProfile]>,
        lastDurationByID: Binding<[String: TimeInterval]>,
        isCalibrating: Bool,
        calibratingVoiceID: String?,
        isPlaying: Bool,
        resolveName: @escaping (_ voiceID: String) -> String,
        timingCellWidth: CGFloat,
        onEdit: @escaping (_ index: Int) -> Void,
        onSync: @escaping (_ voiceID: String) -> Void,
        onDelete: @escaping (_ voiceID: String) -> Void
    ) {
        self._profiles = profiles
        self._lastDurationByID = lastDurationByID
        self.isCalibrating = isCalibrating
        self.calibratingVoiceID = calibratingVoiceID
        self.isPlaying = isPlaying
        self.resolveName = resolveName
        self.timingCellWidth = timingCellWidth
        self.onEdit = onEdit
        self.onSync = onSync
        self.onDelete = onDelete
    }

    public var body: some View {
        // Use indices as row IDs so duplicate voice IDs (same system voice
        // with different pitch/volume) render independently.
        ForEach(Array(profiles.indices), id: \.self) { index in
            let profileValue = profiles[index]
            ChorusLabSelectedVoiceRow(
                name: resolveName(profileValue.id),
                rate: profileValue.rate,
                pitch: profileValue.pitch,
                volume: profileValue.volume,
                duration: lastDurationByID[profileValue.id],
                isCalibrating: calibratingVoiceID == profileValue.id,
                timingCellWidth: timingCellWidth
            )
            .contentShape(Rectangle())
            .onTapGesture {
                onEdit(index)
            }
            .swipeActions(edge: .trailing, allowsFullSwipe: true) {
                // Put Sync first so full-swipe defaults to Sync (safer than Delete).
                Button {
                    onSync(profileValue.id)
                } label: {
                    Label("Sync", systemImage: "arrow.clockwise")
                }
                .disabled(isCalibrating || isPlaying)
                .tint(.blue)
                .accessibilityLabel("Synchronize this voice")
                .accessibilityHint("Calibrate this voice to the target time")

                Button(role: .destructive) {
                    onDelete(profileValue.id)
                } label: {
                    Label("Delete", systemImage: "trash")
                }
                .disabled(isCalibrating || isPlaying)
                .accessibilityLabel("Delete voice")
            }
        }
    }
}

#if DEBUG
@MainActor
internal struct ChorusLabSelectedVoicesSection_Previews: PreviewProvider {
    internal static var previews: some View {
        PreviewWrapper()
            .previewLayout(.sizeThatFits)
            .padding()
    }

    private struct PreviewWrapper: View {
        @State private var profiles: [TTSVoiceProfile] = [
            TTSVoiceProfile(id: "voice.alex", rate: 0.55, pitch: 1.00, volume: 1.00),
            TTSVoiceProfile(id: "voice.alex", rate: 0.60, pitch: 1.25, volume: 0.90),
            TTSVoiceProfile(id: "voice.alex", rate: 0.50, pitch: 0.80, volume: 0.85)
        ]
        @State private var lastDurationByID: [String: TimeInterval] = [
            "voice.alex": 2.48
        ]

        var body: some View {
            List {
                ChorusLabSelectedVoicesSection(
                    profiles: $profiles,
                    lastDurationByID: $lastDurationByID,
                    isCalibrating: false,
                    calibratingVoiceID: nil,
                    isPlaying: false,
                    resolveName: { id in id },
                    timingCellWidth: 48,
                    onEdit: { _ in },
                    onSync: { _ in },
                    onDelete: { _ in }
                )
            }
            .listStyle(.automatic)
        }
    }
}
#endif
