//
//  ChorusLabTargetTimeRow+Init.swift
//  VoiceKitUI
//
//  Convenience initializer for ChorusLabTargetTimeRow with more readable parameter labels.
//
//  Generated by GPT-5 (OpenAI) - collaborator: rdoggett
//  date: 11-13-2025
//

import SwiftUI

/// Convenience initializer with clearer parameter labels (`seconds:` instead of `targetSeconds:`, etc.).
/// Forwards all parameters to the memberwise initializer.
public extension ChorusLabTargetTimeRow {
    init(seconds targetSeconds: Binding<Double>,
         playing isPlaying: Bool,
         lastChorusSeconds: Double?,
         targetRange: ClosedRange<Double>,
         targetStep: Double,
         actualMinWidth: CGFloat) {
        self.init(
            targetSeconds: targetSeconds,
            isPlaying: isPlaying,
            lastChorusSeconds: lastChorusSeconds,
            targetRange: targetRange,
            targetStep: targetStep,
            actualMinWidth: actualMinWidth
        )
    }
}
 
