//
//  ChorusLabGlobalAdjustmentsView.swift
//  VoiceKit
//
//  Global tuning sliders for Chorus Lab (speed × and pitch offset).
//  Generated by GPT-5 (OpenAI) - collaborator: rdoggett
//  date: 10-31-2025
//

import SwiftUI
import VoiceKitUI

@MainActor
public struct ChorusLabGlobalAdjustmentsView: View {
    @Binding var rateScale: Double
    @Binding var pitchOffset: Double
    var speedRange: ClosedRange<Double>
    var pitchOffsetRange: ClosedRange<Double>
    var sliderStep: Double
    var onChange: () -> Void

    // Public memberwise initializer; declaring this in-struct suppresses the synthesized init
    // and avoids redeclaration/ambiguity with a same-signature extension initializer.
    public init(rateScale: Binding<Double>,
                pitchOffset: Binding<Double>,
                speedRange: ClosedRange<Double>,
                pitchOffsetRange: ClosedRange<Double>,
                sliderStep: Double,
                onChange: @escaping () -> Void) {
        self._rateScale = rateScale
        self._pitchOffset = pitchOffset

        self.speedRange = speedRange
        self.pitchOffsetRange = pitchOffsetRange

        self.sliderStep = sliderStep
        self.onChange = onChange
    }

    public var body: some View {
        VStack(spacing: 8) {
            // VoiceTuningControls expects Float bindings; project from our Double state.
            VoiceTuningControls(
                rate: Binding<Float>(
                    get: { Float(rateScale) },
                    set: { newValue in
                        rateScale = Double(newValue)
                        onChange()
                    }
                ),
                pitch: Binding<Float>(
                    get: { Float(1.0 + pitchOffset) },
                    set: { newValue in
                        // newValue is absolute factor; convert back to offset around 1.0
                        pitchOffset = Double(newValue) - 1.0
                        onChange()
                    }
                ),
                volume: nil,
                config: VoiceTuningConfig(
                    showVolume: false,
                    rateRange: Float(speedRange.lowerBound)...Float(speedRange.upperBound),
                    pitchRange: Float(1.0 + pitchOffsetRange.lowerBound)...Float(1.0 + pitchOffsetRange.upperBound),
                    volumeRange: 0.0...1.0,
                    rateStep: Float(sliderStep),
                    pitchStep: Float(sliderStep),
                    volumeStep: nil,
                    rateDecimals: 2,
                    pitchDecimals: 2,
                    volumeDecimals: 2,
                    labelWidth: 64,
                    readoutWidth: 44
                ),
                labels: .default
            )
        }
    }
}

#if DEBUG
@MainActor
internal struct ChorusLabGlobalAdjustmentsView_Previews: PreviewProvider {
    private struct PreviewWrapper: View {
        @State var rateScale: Double = 1.00
        @State var pitchOffset: Double = 0.00
        var body: some View {
            VStack(spacing: 10) {
                ChorusLabGlobalAdjustmentsView(
                    rateScale: $rateScale,
                    pitchOffset: $pitchOffset,
                    speedRange: 0.5...1.5,
                    pitchOffsetRange: -0.5...0.5,
                    sliderStep: 0.01,
                    onChange: {}
                )
                .padding(.horizontal)
                .padding(.vertical, 8)
            }
        }
    }

    internal static var previews: some View {
        PreviewWrapper()
            .previewDisplayName("ChorusLabGlobalAdjustmentsView · iPhone SE (3rd gen)")
            .environment(\.locale, .init(identifier: "en_US"))
            .previewDevice("iPhone SE (3rd generation)")
    }
}
#endif
