//
//  ChorusLabSelectedVoiceRow.swift
//  VoiceKit
//
//  Row displaying selected voice name, compact settings, and last duration.
//  Generated by GPT-5 (OpenAI) - collaborator: rdoggett
//  date: 10-31-2025
//

import SwiftUI
import VoiceKitUI

/// Single-voice row for the chorus list, showing name, rate, pitch, volume, and measured duration.
///
/// Displays:
/// - **Left**: Voice display name (e.g., "Alex", "Victoria").
/// - **Middle**: Compact rate/pitch/volume readout (S 0.55 · P 1.1 · Vol 0.9).
/// - **Right**: Last measured duration, highlighted during calibration.
/// - **Far right**: Disclosure chevron.
///
/// The row is marked as a button for accessibility. Tap opens the tuner; swipe reveals sync/delete actions.
@MainActor
public struct ChorusLabSelectedVoiceRow: View {
    /// Display name of the voice (e.g., "Alex", "Victoria").
    let name: String
    /// Speaking rate (normalized in [0, 1]).
    let rate: Double
    /// Pitch multiplier (typically 0.5 - 2.0).
    let pitch: Float
    /// Relative amplitude (0 - 1).
    let volume: Float
    /// Most recent measured duration for this voice in seconds (nil if not yet measured).
    let duration: TimeInterval?
    /// Whether this voice is currently being calibrated (highlights the duration cell in green).
    let isCalibrating: Bool
    /// Width of the duration cell (injected to control layout).
    var timingCellWidth: CGFloat = 42

    public var body: some View {
        HStack(alignment: .firstTextBaseline, spacing: 8) {
            // Name (left)
            Text(name)
                .font(.subheadline)
                .lineLimit(1)
                .minimumScaleFactor(0.9)
                .allowsTightening(true)
                .truncationMode(.tail)
                .layoutPriority(1)
                .frame(maxWidth: .infinity, alignment: .leading)
                .accessibilityLabel("Voice name")
                .accessibilityValue(Text(name))

            Spacer(minLength: 0)

            // Details (middle)
            DetailsCell(rate: rate, pitch: pitch, volume: volume)
                .accessibilityLabel("Voice settings")
                .accessibilityValue(
                    Text("Speed \(rate.display()), Pitch \(pitch.display()), Volume \(volume.display())"))

            // Timing (right)
            DurationCell(duration: duration, isHighlighted: isCalibrating, width: timingCellWidth)
                .accessibilityLabel("Last duration")
                .accessibilityValue(Text(duration.map { $0.display(suffix: "s") } ?? "Not measured"))

            Image(systemName: "chevron.right")
                .font(.caption2)
                .foregroundStyle(.tertiary)
                .frame(width: 6, alignment: .trailing)
                .accessibilityHidden(true)
        }
        .accessibilityAddTraits(.isButton)
    }
}

// MARK: - Helper cells

/// Compact display of voice profile settings: rate, pitch, volume (3-letter abbreviated format).
/// Example: "S 0.55 · P 1.1 · Vol 0.9" (Speed, Pitch, Volume).
@MainActor
private struct DetailsCell: View {
    /// Speaking rate to display.
    let rate: Double
    /// Pitch multiplier to display.
    let pitch: Float
    /// Volume amplitude to display.
    let volume: Float
    var body: some View {
        Text(["S \(rate.display())",
              "P \(pitch.display())",
              "Vol \(volume.display())"]
            .joined(separator: " · ")
        )
        .font(.caption2)
        .foregroundStyle(.secondary)
        .lineLimit(1)
        .minimumScaleFactor(0.9)
        .allowsTightening(true)
        .frame(minWidth: 150, maxWidth: 220, alignment: .trailing)
    }
}

/// Display of measured duration with optional highlight (for calibration feedback).
/// Shows duration in seconds (e.g., "2.45s"), or empty string if not yet measured.
/// When isHighlighted=true, background turns green to indicate active calibration.
@MainActor
private struct DurationCell: View {
    /// Measured duration in seconds (nil if not yet recorded).
    let duration: TimeInterval?
    /// Whether to highlight this cell (green background during calibration).
    let isHighlighted: Bool
    /// Fixed width for the cell (prevents layout shift as values change).
    let width: CGFloat
    var body: some View {
        let text = duration.map { $0.display(suffix: "s") } ?? ""
        Text(text)
            .font(.footnote)
            .monospacedDigit()
            .foregroundStyle(duration == nil ? .secondary : .primary)
            .frame(width: width, alignment: .trailing)
            .padding(.vertical, 2)
            .background {
                if isHighlighted {
                    RoundedRectangle(cornerRadius: 4)
                        .fill(Color.green.opacity(0.18))
                }
            }
            .animation(.easeInOut(duration: 0.2), value: isHighlighted)
    }
}

#if DEBUG
@MainActor
internal struct ChorusLabSelectedVoiceRow_Previews: PreviewProvider {
    internal static var previews: some View {
        PreviewWrapper()
            .previewLayout(.sizeThatFits)
            .padding()
    }

    private struct PreviewWrapper: View {
        @State private var highlight = true

        var body: some View {
            VStack(alignment: .leading, spacing: 12) {
                ChorusLabSelectedVoiceRow(
                    name: "Alex",
                    rate: 0.55567,
                    pitch: 1.0555,
                    volume: 0.789,
                    duration: 2.4863,
                    isCalibrating: highlight
                )
                ChorusLabSelectedVoiceRow(
                    name: "Samantha",
                    rate: 0.70,
                    pitch: 1.15,
                    volume: 0.90,
                    duration: nil,
                    isCalibrating: false
                )
            }
        }
    }
}
#endif
