name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-14
            xcode: '16.*'
          - os: macos-13
            xcode: '15.*'
    runs-on: ${{ matrix.os }}
    timeout-minutes: 25

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode (Swift toolchain)
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}

      - name: Tool versions
        run: |
          xcodebuild -version
          swift --version

      - name: Cache SPM
        uses: actions/cache@v4
        with:
          path: |
            ~/.swiftpm
            .build
          key: spm-${{ runner.os }}-xcode-${{ matrix.xcode }}-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            spm-${{ runner.os }}-xcode-${{ matrix.xcode }}-

      - name: Resolve
        run: swift package resolve

      - name: Build (debug)
        env:
          NSUnbufferedIO: "YES"
        run: swift build -v

      - name: Test
        env:
          SWIFTPM_TEST_LOG_FORMAT: xcode
          NSUnbufferedIO: "YES"
        run: |
          set -euo pipefail
          echo "Running tests (parallel if supported)..."
          if swift test -h 2>/dev/null | grep -q ' --parallel'; then
            swift test --parallel -v
          else
            swift test -v
          fi
