name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode (Swift 6)
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '16.*'

      - name: Tool versions
        run: |
          xcodebuild -version
          swift --version

      - name: Resolve
        run: swift package resolve

      - name: Build (debug)
        run: swift build -v

      - name: Test
        run: swift test -v
