name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: macos-14
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode (Swift 6)
        uses: maxim-lobanov/setup-xcode@v1
        with:
          # Allow any 16.x to improve scheduling availability
          xcode-version: '16.*'

      - name: Tool versions
        run: |
          xcodebuild -version
          swift --version

      - name: Cache SPM
        uses: actions/cache@v4
        with:
          path: |
            ~/.swiftpm
            .build
          key: spm-${{ runner.os }}-xcode-16-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            spm-${{ runner.os }}-xcode-16-

      - name: Resolve
        run: swift package resolve

      - name: Build (debug)
        run: swift build -v

      - name: Test
        env:
          SWIFTPM_TEST_LOG_FORMAT: xcode
        run: |
          # Run tests in parallel to shorten CI time; verbose for Xcode-style logs
          swift test --parallel -v
          # Print a short summary of durations (optional)
          swift test --show-codecov-path >/dev/null 2>&1 || true
