name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-14, macos-13]
    runs-on: ${{ matrix.os }}
    timeout-minutes: 25

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode (Swift 6)
        uses: maxim-lobanov/setup-xcode@v1
        with:
          # Allow any 16.x to improve scheduling availability
          xcode-version: '16.*'

      - name: Tool versions
        run: |
          xcodebuild -version
          swift --version

      - name: Cache SPM
        uses: actions/cache@v4
        with:
          path: |
            ~/.swiftpm
            .build
          key: spm-${{ runner.os }}-xcode-16-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            spm-${{ runner.os }}-xcode-16-

      - name: Resolve
        timeout-minutes: 5
        run: swift package resolve

      - name: Build (debug)
        timeout-minutes: 10
        env:
          NSUnbufferedIO: "YES"
        run: swift build -v

      - name: Test
        timeout-minutes: 12
        env:
          SWIFTPM_TEST_LOG_FORMAT: xcode
          NSUnbufferedIO: "YES"
        run: |
          set -euo pipefail
          echo "Swift version:"
          swift --version
          echo "Running tests (parallel)..."
          swift test --parallel -v
